### ISSUE TITLE
Videomass portable without install

### ISSUE THREAD

**Issue by candrapersada** [jeanslack/Videomass#10]
how to use Videomass portable for Windows?

**Comment by jeanslack** [comment]
Hi
If by portable you mean a package for Windows containing everything you need to run from anywhere, well it doesn't exist yet.

**Comment by candrapersada** [comment]
add portable features.

**Comment by jeanslack** [comment]
I just don't have much free time now, I'll do it anyway.

**Comment by jeanslack** [comment]
Hey, Videomass portable is coming
