### ISSUE TITLE
Updated Dutch translation

### ISSUE THREAD

**Issue by johannesdedoper** [jeanslack/Videomass#100]
Hello,

I attached the updated Dutch translation.
Cheers,
J.

[videomass.zip](https://github.com/jeanslack/Videomass/files/8371204/videomass.zip)

**Comment by jeanslack** [comment]
Hello,

Thank you very much for this contribution!

**Comment by jeanslack** [comment]
Hello,

I am very grateful to you for the valuable contribution to the Dutch translation that you have updated. However, opening the videomass.po file with the poEdit application I found about fifty lines marked in yellow and 15 not yet translated: 
![poedit](https://user-images.githubusercontent.com/8676484/160947047-63b6183c-ba66-4721-af66-176b675b9310.png)
poEdit successfully compiled the translation file, but it is still incomplete.. Can I ask you which translation program did you use? 

Good night!
G.

**Comment by johannesdedoper** [comment]
Hello, goodmorning,

I just added to the existing translation that was included in the Videomass source.
I translated the new features you implemented and corrected a few Dutch typos.
I saw a few (as you mention 15) things I did not recognize and were not translated but I thought there was a reason for that.

The yellow lines are not my translation as far I can read.
But what does it mean when they are marked yellow?
I can probably correct these if I know what is wrong with them.

BTW, how can I choose the language in Videomass as mine is always on English as all my software is.
Of course I can rename the .po and .mo but is there a menu item or something?

cheers,
J.

**Comment by jeanslack** [comment]
Hello @johannesdedoper,

Thnx, that's okay. If you want you can translate the rest too, no problem. The lines marked in yellow are the lines that were already translated correctly but due to changes made to the original strings (in English) they are to be checked. If they are OK just deselect the `Needs Work` button, otherwise by correcting them that button deselects itself.

> BTW, how can I choose the language in Videomass as mine is always on English as all my software is.

There is no language selection on Videomass, first you should set the preferred language on your system, i.e. Dutch language if you want to do English to Dutch translation with poEdit, but if your system is in English, videomass will also be in English.

Ciao from Italy!

**Comment by johannesdedoper** [comment]
Ok, will have translate the rest. 
I used the Gnome editor before. But I will use the poEDIT in the future. But I do not have poEDIT PRO so I can not see the orange things, at least not all.
Will try doing this this weekend.

BTW I have a question, which I can put in as a new "Issue",  but before that I like to know if it is feasible and/or interesting: The possibility to open the menu items: "Presets manager" and "A/V Conversions" without having to put in a file in the file queue.
This way you do not need to put in a file everytime you want to check/edit your presets or play with the A/V conversions settings.

Cheers,
J.

**Comment by jeanslack** [comment]
OK, feel free to do. Note that I am not using poEdit PRO but the standard version installed from repo of my Devuan Linux box. To see the orange lines scroll down, or go to the View menu and check the "First untranslated entries" check box.

> BTW I have a question, which I can put in as a new "Issue", but before that I like to know if it is feasible and/or interesting: The possibility to open the menu items: "Presets manager" and "A/V Conversions" without having to put in a file in the file queue.
This way you do not need to put in a file everytime you want to check/edit your presets or play with the A/V conversions settings.

Yes, it should be feasible, I have often thought about how to solve this problem. I think I will have to fix it permanently. 

Cheers!

**Comment by johannesdedoper** [comment]
> Yes, it should be feasible, I have often thought about how to solve this problem. I think I will have to fix it permanently.

Ok, it's not really a big issue but it would be nice!

Here the new Dutch translation. Still some things are indicated yellow, however they seem ok to me, as some English words are so commonly used in our Dutch language and should not really be translated.

Cheers
[Dutch v2.zip](https://github.com/jeanslack/Videomass/files/8404798/Dutch.v2.zip)
!

**Comment by jeanslack** [comment]
OK, Thank you very much!
I would love to add you to Videomass credits as a translator and contributor if you like it too. 

Cheers!

**Comment by johannesdedoper** [comment]
Hi, that's nice if you like to, but not really necessary. 

As I said before I really love this encoder! 
What makes it unique?
The FFmpeg presets, the drag/drop feature **together** with the feature moving the source files to a different folder and putting the encoded files in the orginal folder.

Let me explain:

1. Drag/drop
What I do is flatten the folders (so I only see the files no folders), then I select the files I like to encode (eg. based on size) and put them in the queue (drag/drop). This is not possible with Handbrake in Linux!. 

2. The new feature moving source files to trash and putting encoded files in source folder
There are programs that can put the encoded file in the source folder eg. Handbrake. The main difference is that Handbrake can not delete the source files after successful encoding and does NOT have a drop/drag function for files in Linux.  
As I have all files in separate folders I need to go to each folder individually and select each file. That takes a lot of time. 
Than afterwards I have to delete all source files I encoded, again takes time.
Another way to encode files that are in separate folders is to flatten all folders and select all files to encode and put them in a new folder together. Handbrake can than read the complete folder and put them in a queue. BUT than the encoded files will be placed in the new folder and NOT in their original source folder. Than I have to put each encoded file manually in it's original folder (that's takes a lot of time!) and delete the folder with all source files.

3. Creating your own presets through using FFmpeg parameters
This is great to easily fine-tune presets and learn even more about FFmpeg.

There are other programs that can do one or the other but there is no encoder that can do this all! 
So, Videomass saves me a lottttttttt of time and is unique!

Now for something competely different:
I updated the Dutch translation.
Today I set my system language to Dutch to see the context of the text.
So I made some changes in words used.

Cheers, J.
[Dutch_v3.zip](https://github.com/jeanslack/Videomass/files/8420202/Dutch_v3.zip)

**Comment by jeanslack** [comment]
Thanks for your explanation and your feedback, I am currently improving the Timeline editor giving the user the ability to make more accurate selections; I am also implementing new features which I think are nice.

> Now for something competely different:
I updated the Dutch translation.
Today I set my system language to Dutch to see the context of the text.
So I made some changes in words used.

Great! thanks so much!

**Comment by johannesdedoper** [comment]
> I am currently improving the Timeline editor giving the user the ability to make more accurate selections; I am also implementing new features which I think are nice.

Nice to hear. You made me curious ;)
Can't wait..

Ciao,
J.

**Comment by johannesdedoper** [comment]
maybe H.265 NVenc en H.264 NVenc in the "A/V Conversions" drop-down codec list?
And why is it NOT possible to choose bitrate conversion with a single pass conversion, why is this only possible when you choose 2-pass?
I understand the bitrate is variable but still, I would not rule this option out.

**Comment by jeanslack** [comment]
That's right, I'll take a look at it. I will open a new issue for this.
