### ISSUE TITLE
Added Estimated Time of Arrival (ETA) on FFmpeg

### ISSUE THREAD

**Issue by johannesdedoper** [jeanslack/Videomass#101]
Hello,

It's I, Johannes :)
I was looking at the ETA but I think it shows the remaining time of the movie, so the time/position at which it's encoding.
What I mean is: let's say the movie has a duration of 1 hour and 30 minutes, When you look at the TIME indication it's showing 12 minutes and the ETA is showing 1 hour 18 minutes. In the end the encoding only takes up approx 5-8 minutes. So it seems it is showing the part it is currently encoding. Both are, the TIME indication as well as the ETA.
Of course it would be nice if it's showing the remaining time it will take to finish the encoding.

I believe FFmpeg does not support this as is.
Found a topic on this: https://stackoverflow.com/questions/43657722/ffmpeg-calculate-the-remaining-conversion-time#52892656
FFqueue (also open source) seems to have this (somewhat) fixed: http://ffqueue.bruchhaus.dk/Documentation.aspx ........... _About the process: Statistics from FFmpeg are quite odd and often it seems like no work is being done at all. The remaining time and progress bar seems fixed. But FFmpeg is working and you should not panik about the odd statistics_........

What are your thoughts on this?
Cheers,
J.

**Comment by jeanslack** [comment]
Hello Johannes,

I understand what you mean, but I'm not currently interested in that. As soon as I have more time to investigate, maybe I'll do some tests. Theoretically, by having the speed as the X value and the duration as the Y value, a more accurate estimate of the remaining time can be obtained.

Cheers,
G.

**Comment by jeanslack** [comment]
I just added this feature today.
Your links have been useful to me, thanks!

**Comment by johannesdedoper** [comment]
Wow, great news!
Great that I have been of some help.
thnx,
J.

**Comment by johannesdedoper** [comment]
seems to be working fine!!
Great job.
J.
