### ISSUE TITLE
Navigation item "goto" --> "youtube downloader" not working?

### ISSUE THREAD

**Issue by johannesdedoper** [jeanslack/Videomass#105]
Hello, good evening.
How is everything in Italy?

I wanted to test the youtube downloader and tried to go from Presets Manager to go via de menu to the "Youtube Downloader".
Than nothing happens only a text appears in the bottom saying:  "No URLs added yet". Understandable but confusing, better would be to bring you to the HOME menu or directly to the "Youtube Downloader".
Same story when you try to go the "Youtube Downloader" when you are in the A/V Conversions.

BTW, in the picture it shows the text "Jump to the Youtube downloader panel" in the bottom. This is shown before you click on "youtube downloader". So you think you will be taken to the "Youtube downloader panel". However after clicking it shows "No URLs added yet" and nothing happens.

Please see attached screenshot to clarify.
Cheers,
J.
![youtube](https://user-images.githubusercontent.com/100475891/162635726-edcec0ee-7e55-4f4b-98b0-63aef042384d.png)

**Comment by jeanslack** [comment]
Hi, good evening to you.
The good news is that spring has arrived in Italy! only this so far.
And how is everything in the Netherlands?

Regarding the problem, as mentioned here https://github.com/jeanslack/Videomass/issues/100#issuecomment-1086107885

> BTW I have a question, which I can put in as a new "Issue", but before that I like to know if it is feasible and/or interesting: The possibility to open the menu items: "Presets manager" and "A/V Conversions" without having to put in a file in the file queue.
This way you do not need to put in a file everytime you want to check/edit your presets or play with the A/V conversions settings.

I am solving these problems



Ciao
