### ISSUE TITLE
seperate folder for each playlist ?

### ISSUE THREAD

**Issue by tissatussa** [jeanslack/Videomass#11]
when downloading (all) the videos of a NUMBER OF playlists, it would be handy to auto-create a subfolder to save all videos of the concerning playlist !?  Its name could be according to the playlist title.  Then you could add a checkbox in preferences to enable this feature.

**Comment by jeanslack** [comment]
You're right, I'll take a look at it and see what I can do.

**Comment by tissatussa** [comment]
thanks .. while searching / comparing a GUI for youtube-dl, i chose Videomass and i like it .. but i am surpised almost nobody made some issues here at GitHub .. as if your tool is not popular .. i think it's good though ..

i saw some other (minor) shortcomings while using Videomass .. can i suggest these also ?  I'm a Linux user and Python programmer, but i'm mainly interested in the front-end of GUIs and i have a certain view in this.  I could help or inspire you ..

**Comment by tissatussa** [comment]
one more thing now regarding THIS issue : the name of such subfolder should also hold the name of the YouTube USER .. however, i don't know if this is possible at other video websites (and youtube-dl can do many !)

**Comment by jeanslack** [comment]
> thanks .. while searching / comparing a GUI for youtube-dl, i chose Videomass and i like it .. but i am surpised almost nobody made some issues here at GitHub .. as if your tool is not popular .. i think it's good though ..
> 
> i saw some other (minor) shortcomings while using Videomass .. can i suggest these also ? I'm a Linux user and Python programmer, but i'm mainly interested in the front-end of GUIs and i have a certain view in this. I could help or inspire you ..

I'm not sure I can control what popularity entails. I don't want to shoot myself in the foot but...

Anyway, I am open to suggestions and thank you for your availability.  But keep in mind that this tool is mainly a GUI for FFmpeg, and it only provides a simple interface for youtube-dl, enough for basic video download  (perhaps the real gem is download via Format code that Videomass has as an interface).

**Comment by jeanslack** [comment]
> one more thing now regarding THIS issue : the name of such subfolder should also hold the name of the YouTube USER .. however, i don't know if this is possible at other video websites (and youtube-dl can do many !)

I'll gladly take a look at it. I will let you know...

**Comment by tissatussa** [comment]
here are my first remarks and suggestions .. i'm just starting to use Videomass and i might encounter other details etc which might be changed .. ofcourse it's up to you :-)

-----

when downloading & converting many videos of a playlist, the log shows the amount of videos in the list to be processed, eg. :
"[youtube:tab] playlist Advanced Ancient Technology: Downloading 103 videos"
that's OK, but it would be nice to display the current number somewhere at each seperate video, like "[23/103]".

-----

currently, when processing a playlist, the Videomass log has these lines :

[youtube] 9-7Y3UuejOs: Downloading webpage
[download] Destination: /home/roelof/Downloads/Praveen Mohan/Recreating_a_4000_Year_Old_Battery_-_Was_Electricity_Used_in_Ancient_Times.mp4
[Videomass]: DONE !
Done downloading, now converting ...

-OR-

[dailymotion] x5vihc7: Downloading media JSON metadata
[dailymotion] x5vihc7: Downloading metadata JSON
[dailymotion] x5vihc7: Downloading m3u8 information
[download] Destination: /home/roelof/Downloads/dailymotion.com/Jeanne_Moreau_-_vous_parle_de_l_amour_pt._1.mp4
[Videomass]: DONE !
Done downloading, now converting ...

i propose to add an empty line between those 'sections' : it will make the log a little longer, but the user will like this layout .. it makes the processing more clear.

the line "[Videomass]: DONE !" could be changed to :
"[download]: SUCCESS !" (=green or =red when some error message etc)

the line "Done downloading, now converting" could be changed to :
"[converting]: started"
"[converting]: SUCCESS !" (=green or =red when some error message etc)

-----

BTW. I created some GUIs myself, with TKinter and Python .. i also did some programming with ffmpeg, a fantastic tool with lots of options : eg. i created a GUI to stabilize a video .. it can also create a (wide) "duo video" : on the left the original, on the right the stabilized version, so the user can see the result .. for that i use a pre-build ffmpeg binary which has the vidstab module, by John van Sickle, see https://johnvansickle.com/ffmpeg/ .. my tool is not yet on GitHub, it's still a beta version.  Just saying ..

**Comment by tissatussa** [comment]
today i was using your Videomass extensively .. here are some more remarks and suggestions.

-----

on top of the log we see "output viewing console" .. i'm almost sure this is not proper English (but i'm from Holland) .. i think a better text will be "process log".

-----

in the status bar i see "Under processing" .. here also a better English text can be displayed, i propose "Processing videos.." or just "Processing.."

-----

log snippet :

[dailymotion] x4xyolf: Downloading media JSON metadata
[dailymotion] x4xyolf: Downloading metadata JSON
[dailymotion] x4xyolf: Downloading m3u8 information
[download] Destination: /home/roelof/Downloads/dailymotion.com/Peruvian_Roots_Music.mp4
ERROR: giving up after 0 retries
[Videomass]: FAILED !

why ZERO retries? Processing this video failed, but some file remained in the download folder : its name ends with ".mp4.part" but the file is corrupt .. it could have been deleted !?

-----

another issue i encountered twice today : while downloading all (!) videos of a large playlist (about 500 items), the process suddenly ended with many errors :

![videomass_unauthorized](https://user-images.githubusercontent.com/1109281/106204109-b5fdff00-61bc-11eb-8169-d12e10bff552.png)

finally only 8 videos were downloaded, about 11 Gb (!) in total, and in both cases the process took several hours .. it started with downloading an "Access Token" :

![videomass_unauthorized2](https://user-images.githubusercontent.com/1109281/106204125-beeed080-61bc-11eb-9f1b-79611d4453a0.png)

i suspect the Access Token was expired after some time .. maybe this is a bug : you could try to download a new Access Token when this happens, but i have no clue why such error would occur ..

**Comment by jeanslack** [comment]
thanks for your valuable suggestions. Soon I will dedicate time to everything you have listed.

As for the issues above, I might ask you which version of youtube-dl did you use? and how did you set Videomass (in the youtube-dl table preferences)?

**Comment by jeanslack** [comment]
Also, could you open a new issue for these errors?

**Comment by tissatussa** [comment]
> thanks for your valuable suggestions. Soon I will dedicate time to everything you have listed.
> 
> As for the issues above, I might ask you which version of youtube-dl did you use? and how did you set Videomass (in the youtube-dl table preferences)?

very recently i updated my youtube-dl to version 2021.01.24.1 .. i think this is the newest at this moment : executing "youtube-dl --version" in terminal (in any folder) displays that version number .. it's a small python script (about 10 lines) named "youtube-dl" (without '.py') located in /usr/local/bin/youtube-dl because :

$ echo $PATH :
/home/roelof/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/root/.cargo/bin

$ whereis youtube-dl :
youtube-dl: /usr/bin/youtube-dl /usr/local/bin/youtube-dl /usr/share/man/man1/youtube-dl.1.gz

to install / update i followed the instructions of some linux tech article, which mentions that youtube-dl was previously located in /usr/bin but now they changed it to /usr/local/bin .. my PATH is accordingly.  For test (before using Videomass) i did put a print statement in that Python file to be sure this file is executed when doing "youtube-dl --version" in terminal.

Videomass Setup / youtube-dl tab : indeed i looked at this before using Videomass :
* Downloader preferences : "Use the one installed in your O.S."
* Current path : /usr/local/lib/python3.8/dist-packages/youtube_dl : i did not change this .. also, i was not aware this could be a wrong setting .. however, in /usr/local/lib/python3.8/dist-packages/youtube_dl (which is a folder!) many .py files are located .. also a small 'version.py' which just has the line __version__ = '2021.01.24.1' .. I don't know how these 2 youtube-dl programs are connected / the same, but i guess it's OK.

**Comment by tissatussa** [comment]
> Also, could you open a new issue for these errors?

OK .. keep my text and screenshots in this issue also ?

**Comment by jeanslack** [comment]
See [#13](https://github.com/jeanslack/Videomass/issues/13)

**Comment by jeanslack** [comment]
@tissatussa 
Playlists now have separate folders. Some things have been fixed.
