### ISSUE TITLE
Login/Pass

### ISSUE THREAD

**Issue by Ferl67** [jeanslack/Videomass#114]
Hi. Your software is amazing. Just one question. There's something I want to download from a website which requires a login/password. Is there any way to pass that info to yt_dlp ?
I found this other software, TVDownloader which can do this but it doesn't work as well as yours. ;)

**Comment by jeanslack** [comment]
Hi @Ferl67,

Thanks for the appreciation, I am really pleased!

To answer you, I have personally never used authentication with youtube_dl nor with yt_dlp, so I can't give you an answer.
Furthermore Videomass does not support authentication and I have not planned to implement it in order not to overload the program with such specific and advanced functions.

> I found this other software, TVDownloader which can do this but it doesn't work as well as yours. ;)

I've never used TVDownloader (I'll check it out anyway) but I tried youtube-dl-gui and it seemed to me that it could support authentication: https://github.com/oleksis/youtube-dl-gui
Another very complete program that should support authentication is Tartube: https://github.com/axcore/tartube
