### ISSUE TITLE
Videomass failed : giving up after 0 retries ?

### ISSUE THREAD

**Issue by tissatussa** [jeanslack/Videomass#12]
log snippet :

[dailymotion] x4xyolf: Downloading media JSON metadata
[dailymotion] x4xyolf: Downloading metadata JSON
[dailymotion] x4xyolf: Downloading m3u8 information
[download] Destination: /home/roelof/Downloads/dailymotion.com/Peruvian_Roots_Music.mp4
ERROR: giving up after 0 retries
[Videomass]: FAILED !

why ZERO retries? Processing this video failed, but some file remained in the download folder : its name ends with ".mp4.part" but the file is corrupt .. it could have been deleted !?

**Comment by jeanslack** [comment]
@tissatussa, it could be the same issue as [13](https://github.com/jeanslack/Videomass/issues/13)
