### ISSUE TITLE
Feature Request: Option to Manually select language

### ISSUE THREAD

**Issue by katnatek** [jeanslack/Videomass#127]
Some times the language detector of the application is not accurate, in my case i have to install english language tools among the spanish and that affect the language of the application (starts in english), i have to run videomass with

` LC_ALL=es videomass`

To get the spanish language in the application

**Comment by jeanslack** [comment]
Hi @katnatek,

I am trying to implement your request. I will need your help possibly to test the source code.

**Comment by katnatek** [comment]
> Hi @katnatek,
> 
> I am trying to implement your request. I will need your help possibly to test the source code.

Sure, when you have something give me the link to commit and test as soon as posible

**Comment by jeanslack** [comment]
Hi @katnatek,

I merged everything in the master branch, if there are other problems let me know, thanks.

**Comment by katnatek** [comment]
I make test as soon as possible.  sorry for the delay

**Comment by katnatek** [comment]
Works fine , even start by default in spanish, i test change to english and works as expected,  thank you

**Comment by jeanslack** [comment]
Thanks to you for testing, then I will release a new version soon.
