### ISSUE TITLE
Auto Rename Downloads with Same Name

### ISSUE THREAD

**Issue by Neipas09** [jeanslack/Videomass#130]
It's annoying that I can only download 1 video at a time when using URL's for m3u8.
It would be nice if I add 10 URL's that all end up being named "layer7_bk-layer7.mp4" to being auto-renamed to something like... 
layer7-bk-layer7-1.mp4
layer7-bk-layer7-2.mp4
layer7-bk-layer7-3.mp4
etc...

**Comment by jeanslack** [comment]
Could you tell me what was the procedure you used step by step? I have never used m3u8 files with Videomass and in any case the playlist download process consists of one file at a time.
Can you leave me some sample URLs for testing?
Thanks
