### ISSUE TITLE
Libsvtav1 codec option

### ISSUE THREAD

**Issue by BuyMyMojo** [jeanslack/Videomass#132]
With svt-av1 entering 1.0/1.1 and being implemented into ffmpeg nativley I'd love to see that added to the list of video codecs

**Comment by jeanslack** [comment]
Ok, I'll see what I can do. In the meantime, use the presets manager by creating presets with that codec.

**Comment by jeanslack** [comment]
At the moment it is not possible to add the AV1 encoder to the Videomass **A/V Conversion** function. Several stages of testing are required and this takes a lot of work and time. As a workaround I created a new preset to import on the Presets Manager function which includes the AV1 encoder (specifically libsvtav1 and libaom-av1).
Please, visit the [Videomass-presets](https://github.com/jeanslack/Videomass-presets) page for more explanations on using presets.
