### ISSUE TITLE
Enable opus and vp9 for mp4 container

### ISSUE THREAD

**Issue by BuyMyMojo** [jeanslack/Videomass#133]
According to the [Comparison of video container formats](https://en.wikipedia.org/wiki/Comparison_of_video_container_formats) wiki page and general testing with ffmpeg, vp9 and opus audio are compatable with the mp4 container

**Comment by jeanslack** [comment]
Yes, but you can save yourself a preset with codecs vp9/opus and change the format of the output container to mp4.

**Comment by BuyMyMojo** [comment]
When I set the codec to vp9 I can only choose webm
![Videomass_nQ6iFFOSD9](https://user-images.githubusercontent.com/46948241/173059034-3b6caaa9-c47c-49eb-9063-233a137dc506.png)
