### ISSUE TITLE
bugs, ideas and tips (v3.3.7)

### ISSUE THREAD

**Issue by tissatussa** [jeanslack/Videomass#14]
I installed the (latest) version 3.3.7 by pip.
In the past days I used this Videomass extensively and i wrote notes.
Here are some bugs (i hope i'm right and you can reproduce them), and also ideas and tips.

=====

the layout of some Videomass Wizard screens is wrong (at my Xubuntu 20.04 with XFCE) : the texts are longer and not fully visible :

![Videomass error](https://user-images.githubusercontent.com/1109281/107164456-5f0fdb00-69af-11eb-8774-ad6f8ba37a8e.png)

![Videomass error2](https://user-images.githubusercontent.com/1109281/107164463-63d48f00-69af-11eb-9f20-ef0e51fb9a1f.png)

=====

very nice : the original date-time stamp of a video file is preserved !

======

very nice : all downloaded video files of a playlist have the index number as a prefix, and when more than 9 videos are downloaded the index number has two digits, so the file list can be sorted alphabetically. Indeed this is good practice. (I assume the same happens when more then 99 videos are downloaded, then each prefix index number should have 3 digits -- i did not test this)

======

while downloading many playlists (one by one) with Videomass, i encountered something strange.
Eg. a YouTube playlist had 35 videos and the log message indeed showed **"[youtube:tab] playlist Ancient Aliens in Cambodia: Downloading 35 videos"**, but only 34 were processed .. one was missing, showing this log message :

**[youtube] ugpPeoK7nzw: Downloading webpage
[Videomass]: SUCCESS !
Done downloading, now converting ...**

So, here the line **"[download] Destination: ..."** was missing.

i examined this and i discovered the concerning playlist has two videos which are exactly the same : same title, same duration, same thumbnail, even same URL (!? /watch?v=...&list=...) only the index= differs !? Maybe Videomass detected the video was already downloaded .. i wonder if this is a YouTube bug or the playlist owner uploaded the same video twice ..

=====

IDEA : option : include the (YouTube) video ID in the file name .. some video downloaders have this option .. you could create a checkbox for this.

======

here is a video which had troubles, it could not be downloaded .. it's from the playlist "Singapore" from the YouTube channel of Praveen Mohan :

_Halloween at Singapore - Fright Nites 4D Adventureland 2014_
https://www.youtube.com/watch?v=UrMdAPql9-A&list=PLxcxfvUxdiDSOOXMwm8ELmclI9vppTmal&index=7

this part of the log is relevant :

**[youtube] UrMdAPql9-A: Downloading MPD manifest
ERROR: giving up after 0 retries
[Videomass]: FAILED !**

luckily, the download addon of SaveFrom.net, for FireFox & Chrome, shows some info in its tooltip while hovering over the selectbox option "mp4 720 HD" (best quality of this video) which has a red exclamation mark : "Unable to get the file size. Please try again." .. I guess this might give some insight why Videomass failed .. however, the SaveFrom addon has a second "mp4 720 HD" option, which i used to download that video.

same with the video https://www.youtube.com/watch?v=Q_8lfblCwhI :

**[youtube] Q_8lfblCwhI: Downloading webpage
[youtube] Q_8lfblCwhI: Downloading js player f6ef8aad
[youtube] Q_8lfblCwhI: Downloading js player f6ef8aad
[youtube] Q_8lfblCwhI: Downloading MPD manifest
ERROR: giving up after 0 retries
[Videomass]: FAILED !**

=====

the error "giving up after 0 retries" and "[Videomass]: FAILED !" remains while downloading some files .. i had this experience with some BitChute videos, eg. :

**URL 1/1 : "https://www.bitchute.com/video/dZFgwbzEBbS4/?list=notifications&randomize=false"
[BitChute] dZFgwbzEBbS4: Downloading webpage
[BitChute] dZFgwbzEBbS4: Checking video URL
[download] Destination: /home/roelof/Downloads/ALCYON_PLEIADES_104_-_VACCINE_REFUSAL_DEATHS_EFFECTS_GLOBAL_RESISTANCE_AGENDA_21_GROWING_PROTESTS.mp4
ERROR: giving up after 0 retries
[Videomass]: FAILED !

[Videomass]: completed, but not everything was successful.**

The Downloading stops at some % (shown at the bottom of the log window) and a file remains in the download folder, called (filename).mp4.part .. when clicking the 'Download' button again, the download is resumed! So, this is a manual 'retry' .. the first time i tried this, the video file was succesfully completed !  (i don't know if this will happen everytime with a BitChute video, this platform is a bit buggy). You could mention this 'manual retry / resume' option for the user by some message, or you could code an auto-retry : not "giving up after 0 retries".

=====

the text of the checkbox "Download all playlist" could better be "Download all videos in playlist"

=====

when i click "Abort" while downloading a playlist, the status bar shows a yellow message that the process is being aborted .. after a (rather) long time a purple message comes "[Videomass]: Interrupted Process !" but it seems ALL videos WERE STILL downloaded !?

=====

when a URL like https://www.youtube.com/watch?list=PLdT3OotRiHJmYYfi904rgcmbnsVkH4IwY&index=3 is given (here the "v=[videoID]" parameter is missing), i would expect ONLY the 3rd (index=3) video of that playlist is downloaded, but ALL videos are downloaded !?

=====

when i give the URL https://www.youtube.com/watch?v=gyue2X1ho0U , which is just that 3rd video of that playlist, the checkbox "Download all playlist" can be checked. Then a playlist folder structure is created but only the single video is downloaded : Videomass does not know this video belongs to a playlist, and the playlist folder name is "NA" (from title "N/A") .. this is understandable, but i think in this case it's handy and logical to GRAY OUT that checkbox ..

=====

when i give a playlist URL like https://www.youtube.com/playlist?list=PLdT3OotRiHJkyvJNPsY37Auj_N_6Jzq0o (which has 16 videos now) the title column of the Youtube Downloader window shows "N/A" : the name of the concerning playlist is not retrieved, however the created playlist folder structure DOES have the proper name ..

=====

in the Youtube Downloader window, the URL list has a checkbox next to each item .. what does it do?
If i do NOT check it, the video / playlist is still downloaded !?

=====

so, indeed you created a playlist folder structure ! : a folder which has the name of the concerning playlist, and a subfolder which has the name of the (YouTube) user .. that's nice, but i think the folder / subfolder structure should be switched !?

I mean 
[download] Destination: /home/roelof/Downloads/Custom_Chess_Position_Challenge/**Eric_Rosen**/05 - Missing_Both_Rooks.mp4
should better be
[download] Destination: /home/roelof/Downloads/**Eric_Rosen**/Custom_Chess_Position_Challenge/05 - Missing_Both_Rooks.mp4

=====

during download and convert of all playlist videos, the log list keeps growing and it auto-scrolls nicely, so we always see the last processed file .. but after all videos are processed, the auto-scroll is NOT fully done : the final message "[Videomass]: Successfully completed !" is not visible. This is a minor bug, but a bit annoying ..

**Comment by jeanslack** [comment]
Hi @tissatussa,
thanks for reporting.
I will evaluate what to do as soon as possible.

**Comment by jeanslack** [comment]
## I'll answer you in the order of the problems you have opened. (it would be better, however, to open an issue for each one, maybe next time) 


> the layout of some Videomass Wizard screens is wrong (at my Xubuntu 20.04 with XFCE) : the texts are longer and not fully visible :

I fixed the truncated text displayed in the wizard dialog now.

> (I assume the same happens when more then 99 videos are downloaded, then each prefix index number should have 3 digits -- i did not test this)

Of course

> while downloading many playlists (one by one) with Videomass, i encountered something strange.
 
This is a server side youtube error. See https://github.com/ytdl-org/youtube-dl/issues/21660
Solution: Try Downloading by Format Code. E.g. I was successful in downloading that video at 1920x1080 (1080p) 
![FC](https://user-images.githubusercontent.com/8676484/107491534-9509b680-6b8b-11eb-8f9c-f62abdea87c6.png)

> the error "giving up after 0 retries" and "[Videomass]: FAILED !" remains while downloading some files .. i had this experience with some BitChute videos, eg. 

I had no problem downloading from BitChute (youtube-dl version 2021.02.04.1)
![Success](https://user-images.githubusercontent.com/8676484/107491886-0d707780-6b8c-11eb-8a56-0c08fb99970a.png)

> the text of the checkbox "Download all playlist" could better be "Download all videos in playlist"

That is youtube-dl default output given by debugs, warnings and errors messages from logger object. I can't (and don't want to) change it. 

> when i click "Abort" while downloading a playlist, the status bar shows a yellow message that the process is being aborted .. after a (rather) long time a purple message comes "[Videomass]: Interrupted Process !" but it seems ALL videos WERE STILL downloaded !?

I know, this is an annoying lack. Check #8 
Workaround: menu bar > Settings > Preferences > tab youtube-dl, and choose: "Use a local copy of youtube-dl updatable by Videomass". Then Restart Videomass. This way the Abort button should work. 

> when a URL like https://www.youtube.com/watch?list=PLdT3OotRiHJmYYfi904rgcmbnsVkH4IwY&index=3 is given (here the "v=[videoID]" parameter is missing), i would expect ONLY the 3rd (index=3) video of that playlist is downloaded, but ALL videos are downloaded !?

Strange, from my browser that link gives me:: YouTube is not currently available on this device.
However, if I download from a URL like https://www.youtube.com/watch?v=I7_c8Z90osg&list=PL_Ybd3jiyiLcVtx0jAiXNeCA6Kr5lts51&index=2 ONLY the 2rd (index=2) video of that playlist is downloaded, not all videos.

> when i give a playlist URL like https://www.youtube.com/playlist?list=PLdT3OotRiHJkyvJNPsY37Auj_N_6Jzq0o (which has 16 videos now) the title column of the Youtube Downloader window shows "N/A" : the name of the concerning playlist is not retrieved, however the created playlist folder structure DOES have the proper name ..

N/A in the Title column must be fixed (never give the title, unless you choose Download by format code). But it should never cause the playlist name to be missing in the directory structure. I'll go into it anyway. 

> in the Youtube Downloader window, the URL list has a checkbox next to each item .. what does it do?
If i do NOT check it, the video / playlist is still downloaded !?

That checkbox is useless, but it's impossible to remove. I think it is a small bug of wxPython version 4.0.4. In the latest versions this problem is solved. If you want you can install wxPython 4.1.1 for Ubuntu 20.04:
`pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython`
But first remove the system one: `sudo apt remove python3-wxgtk4.0`

> so, indeed you created a playlist folder structure ! ...should better be
[download] Destination: /home/roelof/Downloads/Eric_Rosen/Custom_Chess_Position_Challenge/05 - Missing_Both_Rooks.mp4

OK 
In addition I will also add the video ID option in the file name with a checkbox for this. 

> during download and convert of all playlist videos, the log list keeps growing and it auto-scrolls nicely, so we always see the last processed file .. but after all videos are processed, the auto-scroll is NOT fully done : the final message "[Videomass]: Successfully completed !" is not visible. This is a minor bug, but a bit annoying ..

I noticed ..I think I fix it

**Comment by tissatussa** [comment]
thank you for your work and info !  Indeed, it's better to have separate issues, so comments are more clear .. however, i had many small issues, so i put them in one text .. but next time i will start an issue for each tip/idea/bug : also my replies to the answers you gave will be new issues now -- for that i will quote the ones mentioned here.
