### ISSUE TITLE
Stay blocked at "Downloading android player API JSON"

### ISSUE THREAD

**Issue by breatfr** [jeanslack/Videomass#141]
Hi,

Videomass v4.0.1 stay blocked at "Downloading android player API JSON" when I want download a video with yt-dlp.

How can I fix it ?

**Comment by jeanslack** [comment]
Hi,
Which OS are you using?
Which Videomass installer did you use?
Version of yt-dlp?
Does this problem manifest itself when downloading each video?
Can you take a screenshot and drag it here?

**Comment by breatfr** [comment]
hi,
i'm on linux mint 21 and tryed on linux mint 20.3 too with same problem.
i installed videomass with this command : `python3 -m pip install videomass`
yt-dlp version : 2022.04.08-1
the problem come for all videos and i tryed only with youtube video
unfortunatly no because i remove them actually but the message was :"Downloading android player API JSON"

that works with yt-dl but very very very slow so not usable.

waiting i used a windows application in wine to dl and that works

**Comment by jeanslack** [comment]
I just installed Videomass using your same command, and had no problems downloading the videos.
yd-dlp version 2022.08.08
![Screenshot_20220811_125343](https://user-images.githubusercontent.com/8676484/184099595-ebaf475a-dde5-4835-9f1e-3dc0744f1e74.png)
![Screenshot_20220811_125411](https://user-images.githubusercontent.com/8676484/184099625-dfb3a7af-b1fe-46e1-a8c2-894498c49b52.png)

**Comment by breatfr** [comment]
ok, didn't saw the new version of yt-dlp. i installed it from the software manager in mint.

I reinstalled videomass from your ppa (can't run it with pip installed version) and yt-dlp with pip and seams works now :)

additionnal question : videomass works only for youtube ?

**Comment by jeanslack** [comment]
> additionnal question : videomass works only for youtube ?

Videomass is just a [youtube-dl](https://youtube-dl.org/) and [yt-dlp](https://github.com/yt-dlp/yt-dlp) based interface, and it works on all video sites supported by these downloaders.

Here you find a list of supported sites:
http://ytdl-org.github.io/youtube-dl/supportedsites.html
