### ISSUE TITLE
Videomass' yt_dlg plugin gets stuck on updating . . .

### ISSUE THREAD

**Issue by MartinVonReichenberg** [jeanslack/Videomass#142]
Hello,

The _yt_dlg_ _(`yt-dlg`)_ is stuck at the loading screen while updating . . .

I tried it several times, even in the past and it still the same since then.

SCREENSHOT:
![Screenshot_20220810_101412](https://user-images.githubusercontent.com/110736521/183850818-68641a0b-9cf0-47da-b753-946fcf48990f.png)

Thank you for solving it in advance,
Martin from Czechia

**Comment by jeanslack** [comment]
Hello @MartinVonReichenberg 
Which Linux distribution are you using?
I also recently had this problem on Manjaro Linux.

**Comment by MartinVonReichenberg** [comment]
@jeanslack 
This was taken from an **Arch based** Linux distro called **Garuda Linux** _(Garuda-KDE-Lite)_. 
I can imagine this happens on every distribution....

**Comment by jeanslack** [comment]
> I can imagine this happens on every distribution....

No it doesn't happen in every Linux distribution, not on Ubuntu for example. Usually on Linux the login shell is **/bin/bash** I don't know why Arch-Linux based distributions use a different login shell.
However this problem happens when the default shell is not **bash** but another shell like **zsh** or other, or when the xterm emulator is not installed.

Before updating the Videomass AppImage you should make sure that the default shell is set to **/bin/bash** and that the **xterm** terminal emulator is installed as well.

https://www.cyberciti.biz/tips/how-do-i-find-out-what-shell-im-using.html
https://www.cyberciti.biz/faq/howto-change-linux-unix-freebsd-login-shell/

Let me know!

**Comment by MartinVonReichenberg** [comment]
> > I can imagine this happens on every distribution....
> 
> No it doesn't happen in every Linux distribution, not on Ubuntu for example. Usually on Linux the login shell is **/bin/bash** I don't know why Arch-Linux based distributions use a different login shell. However this problem happens when the default shell is not **bash** but another shell like **zsh** or other, or when the xterm emulator is not installed.
> 
> Before updating the Videomass AppImage you should make sure that the default shell is set to **/bin/bash** and that the **xterm** terminal emulator is installed as well.
> 
> https://www.cyberciti.biz/tips/how-do-i-find-out-what-shell-im-using.html https://www.cyberciti.biz/faq/howto-change-linux-unix-freebsd-login-shell/
> 
> Let me know!



Do you mean the pre-installed _**Terminal**_ (GNOME, KONSOLE, XFCE) ??
Or the _**TTY Shell**_ configurable via _passwd_ command inside _/etc/passwd_ text file ??


Thanks !


It is the same with Ubuntu in my case:
![Screenshot from 2022-08-23 12-41-01](https://user-images.githubusercontent.com/110736521/186138646-7ec14e22-b779-4a73-a2ff-f3a35581a508.png)

**Comment by jeanslack** [comment]
> Do you mean the pre-installed Terminal (GNOME, KONSOLE, XFCE) ??
Or the TTY Shell configurable via passwd command inside /etc/passwd text file ??

I mean the program called **xterm**, which is a terminal emulator installed on most Unix-like systems by default.

The one shown by your screnshot is another issue, I will do some checks to correct it. Now I'm on Devuan Linux and it seems like that problem isn't there, I'll try using Ubuntu.

**Comment by MartinVonReichenberg** [comment]
> > Do you mean the pre-installed Terminal (GNOME, KONSOLE, XFCE) ??
> Or the TTY Shell configurable via passwd command inside /etc/passwd text file ??
> 
> I mean the program called **xterm**, which is a terminal emulator installed on most Unix-like systems by default.
> 
> The one shown by your screnshot is another issue, I will do some checks to correct it. Now I'm on Devuan Linux and it seems like that problem isn't there, I'll try using Ubuntu.
> 


So by changing to  `/bin/bash`in **xterm** it will fix the issue ?_?

**Comment by jeanslack** [comment]
@MartinVonReichenberg 

I just removed the feature to update downloaders using the AppImage, see #152 for some details.
