### ISSUE TITLE
Option to Rename Output File

### ISSUE THREAD

**Issue by Woolwit** [jeanslack/Videomass#144]
Thank You for this marvelous piece of kit!
I noticed today when I was trying to resize a video that was already in my default download location that, while I was warned and asked if I wanted to overwrite the file, I could not see an easy way to rename the output file. My options seemed to be only to move the source video to a different location and start again. I'm probably missing something, but thought to pass on as an FYI.
Videomass v3.5.8
![Screen Shot 2022-08-13 at 19 16 33](https://user-images.githubusercontent.com/3462081/184519889-0fa6ee30-c7c7-4874-b780-81bad3e0bfd6.jpg)

**Comment by jeanslack** [comment]
Hello @Woolwit,
Currently there is no way to name the output files, but you can set a specific destination in the setup options and add a prefix to the names for the output files. However, I will keep this request in mind and see what I can do.

**Comment by Woolwit** [comment]
Hello jeanslack! Thank You! In my setup I'm seeing where the column would be but not having the option to click and edit an Output File Name. I have a default folder set. I also tried with 'Save each file in the same folder as input file' selected.
![Screen Shot 2022-12-03 at 11 44 19](https://user-images.githubusercontent.com/3462081/205459339-65881e88-a974-4187-9cf4-57f925018522.jpg)

**Comment by jeanslack** [comment]
Hello Woolwit,
Which file did you download?

**Comment by Woolwit** [comment]
![image](https://user-images.githubusercontent.com/3462081/205460206-9234abe8-2fdc-42a0-b16d-5d442aecd10a.png)

**Comment by jeanslack** [comment]
Ah ok, I thought you had a chance to try the source code. It 'does not matter.
Anyway I added that feature to the development files, but you'll have to wait for the new release.

**Comment by Woolwit** [comment]
Got it. I will look into understanding how to download/run source code. Thank You!
