### ISSUE TITLE
How do you update yt-dlp?

### ISSUE THREAD

**Issue by formlessdao** [jeanslack/Videomass#147]
I did not find any instructions on how to update yt-dlp.
Can you tell me please how to do it?

Also there are websites where authentication with username and password is needed...how do you log in properly using Videomass so yt-dlp actually works on those websites?

**Comment by jeanslack** [comment]
@formlessdao 

If you intend to update yt-dlp using installers like Videomass.exe or Videomass.dmg, well it's not possible.
If you plan to update those applications frequently, I recommend you to use Videomass on a Python environment and install, update, remove as many packages as you want.

Also, Videomass authentication is not supported, and I have no plans to support this feature in the future.
