### ISSUE TITLE
Unable to open certain videos

### ISSUE THREAD

**Issue by starsang1995** [jeanslack/Videomass#148]
Hi when using 4.0.1, I have found out some videos can be open while others can't (not show in list neither by drag and drop nor by "File - Open"). This is very strange and I don't know why.

**Comment by dr-SeReB** [comment]
Seconded. Opening/dropping files with diacritics (like č Ř ž š ť ň Ů) produces no results.

**Comment by jeanslack** [comment]
@apsonandtesla @dr-SeReB 

I did some tests and found the problem which I will fix soon. It affects name encoding during all sub-processes with ffprobe, ffplay and ffmpeg.

Thanks for reporting this issue.
