### ISSUE TITLE
Cropping video using timeline

### ISSUE THREAD

**Issue by avanlex** [jeanslack/Videomass#150]
It is difficult to set the video cropping time. You have to calculate the start time and end time of the video in Excel using the duration (cropping range = start time + duration). In addition, the combobox for selecting accuracy does not affect the time setting when using the mouse, but only when using the keyboard. The scenario is as follows: you need to select the accuracy, then click on the slider slider, and then move the slider using the keyboard arrows to the right or left. 
Please replace the sliders with two text input fields: start time and end time in the form of HH:MM:SS

**Comment by jeanslack** [comment]
> It is difficult to set the video cropping time. You have to calculate the start time and end time of the video in Excel using the duration (cropping range = start time + duration).

What data would you like to be shown precisely?

> In addition, the combobox for selecting accuracy does not affect the time setting when using the mouse, but only when using the keyboard. The scenario is as follows: you need to select the accuracy, then click on the slider slider, and then move the slider using the keyboard arrows to the right or left.

Yes, it is also reported in the tooltip: _Set the amount of steps the slider moves using 'UP' or 'DOWN' arrow and 'UP' or 'DOWN' page, to quickly set a more accurate time selection_
That's not a problem, at least for me. Unfortunately it was not possible for me to influence the actions of a mouse as well.

> Please replace the sliders with two text input fields: start time and end time in the form of HH:MM:SS

I would only do this if there were dedicated controls for the purpose, a couple of text fields aren't enough; if I have the time to create something I will.

In the meantime, I'm developing this workaround:

![timeline](https://user-images.githubusercontent.com/8676484/204772601-809387d4-7599-4e08-bc92-0b12b936ee24.png)

That button would display this control dialog

![Adjustment](https://user-images.githubusercontent.com/8676484/204773040-090e0b02-b8f0-455f-947c-19a498693613.png)

**Comment by avanlex** [comment]
thank you, you did great
