### ISSUE TITLE
Non latin names in path (solution proposal)

### ISSUE THREAD

**Issue by avanlex** [jeanslack/Videomass#153]
If path contains cyrillic cp1251 (or may be another non latin) symbols error occures: `File does not exist: D:\РїСѓС‚СЊ\С„Р°Р№Р».mp4`
I found that happens because **FFPROBE** returns UTF-8 encoded JSON. But python reads it in system default locale.
Below is my workaround to recode string back to UTF-8. I'm not developer so may be kinda inconsistent. But I googled out such solution to recover encoding. I dont know how to contribute it correctly. Hope it helps somebody. 

📄**ffprobe.py** :
```python
import locale
"""other definitions"""
def ffprobe(filename, cmd='ffprobe', **kwargs):
    """ blah, blah, blah"""
    try:
        with Popen(args,
                   """ blah, blah, blah"""
                   ) as proc:
            output, error = proc.communicate()

            """ Code below is works for me: """
            locale_encoding = locale.getdefaultlocale()[1]
            output = output.encode(locale_encoding).decode("utf-8")
            """ End of my code"""

            if proc.returncode != 0:
                return(None, f'ffprobe: {error}')

    except (OSError, FileNotFoundError) as excepterr:
        return(None, excepterr)
    else:
        return json.loads(output), None
```

**Comment by jeanslack** [comment]
Thanks, I'll take a look at it. It probably concerns this problem as well #148

**Comment by jeanslack** [comment]
> If path contains cyrillic cp1251 (or may be another non latin) symbols error occures: `File does not exist: D:\РїСѓС‚СЊ\С„Р°Р№Р».mp4`

Your URL contains a backslash, which is not allowed on Windows. Anyway I did the test and I understood the problem that I will solve soon. 
Your workaround didn't work with filenames that have characters like **č Ř ž š ť ň Ů** .
