### ISSUE TITLE
Adding support for twitch-dl

### ISSUE THREAD

**Issue by Kamizol** [jeanslack/Videomass#167]
I've been using twitch-dl for quite a while now, and as there is less and less good twitch downloading tools I'm wondering if it's possible to integrate twitch-dl to videomass as it is kinda based on youtube-dl.
As anyone thought of that already, or is it a bad/too complicated idea ?

**Comment by jeanslack** [comment]
Do you have a reference to a web page?
I found this https://github.com/ihabunek/twitch-dl but not sure.
