### ISSUE TITLE
Arch Linux AUR package

### ISSUE THREAD

**Issue by Popolon** [jeanslack/Videomass#168]
Didn't know where to write it, but I added an Arch Linux AUR package.

https://aur.archlinux.org/packages/videomass

Can be installed by using pacaur/yay/etc. After activating AUR on Arch Linux, or in AUR part of Manjaro (Arch Linux derivative) Linux

**Comment by jeanslack** [comment]
Nice!
I will update the webpage https://jeanslack.github.io/Videomass/Pages/Packages/Linux.html by adding this reference.

**Comment by jeanslack** [comment]
I just updated the web page with your URL referring to Videomass AUR package: https://jeanslack.github.io/Videomass/Pages/Packages/Linux.html#archlinux

Thank you very much!
