### ISSUE TITLE
Videomass on windows locale issue

### ISSUE THREAD

**Issue by laundmo** [jeanslack/Videomass#17]
On Windows 10 20H2 10.0.19042 Build 19042

running videomass from the installed didn't work at all, heres the output when running from python REPL.
```
>>> from videomass3 import Videomass3
>>> Videomass3.main()
Win32 executable=C:\Python39\python.exe
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\videomass3\Videomass3.py", line 175, in OnInit
    self.wizard(pathicons[0])
  File "C:\Python39\lib\site-packages\videomass3\Videomass3.py", line 231, in wizard
    main_frame = Wizard(wizardicon)
  File "C:\Python39\lib\site-packages\videomass3\vdms_dialogs\wizard_dlg.py", line 665, in __init__
    self.pageOne = PageOne(self, icon_videomass)  # start...
  File "C:\Python39\lib\site-packages\videomass3\vdms_dialogs\wizard_dlg.py", line 88, in __init__
    bitmap = wx.Bitmap(icon, wx.BITMAP_TYPE_ANY)
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
OnInit returned false, exiting...
```

And here are my locale settings in windows:
![image](https://user-images.githubusercontent.com/24855949/109117735-ad103700-7742-11eb-855b-6d8221b383f7.png)

**Comment by jeanslack** [comment]
Hi, 
this is weird. I have never had any problems with localizations so far. If a language is not found or not translated yet, it should go with the English language by default. Can I ask you which version of wxPython you are using?

**Comment by laundmo** [comment]
relevant pip freeze output

wxPython==4.1.1
Pypubsub==4.0.3
requests==2.25.1

**Comment by jeanslack** [comment]
Unfortunately I have not been able to reproduce this bug on my Windows PC (Windows10, Python3.8, wxPython4.1.1, videomass3.3.8  installed by pip)
Anyway, it seems the problem is the same as this: https://github.com/wxWidgets/Phoenix/issues/1751

**Comment by jeanslack** [comment]
Hi @laundmo, 

In reference to this comment: https://github.com/wxWidgets/Phoenix/issues/1751#issuecomment-678762430
Have you tried doing a little png cleanup?
Have you tried using Python3.7 instead of Python3.9?
Do the above attempts still give you problems? 

Sorry if I insist, but I would like to understand and solve this problem.

**Comment by laundmo** [comment]
@jeanslack Im sorry, I have no clue what you mean by "PNG cleanup" and the issue you're referring to makes no sense at all. What PNGs would I clean up? What folder? Do you mean the PNGs shipped with videomass?

i have tried running with python 3.7 and i still get the exact same issue.

after some more digging i stumbled across [this thread](https://discuss.wxpython.org/t/a-few-more-windows-locale-related-remarks/34788) suggesting that locales in windows are just completely broken, as python itself doesn't recognize locales such as `en-GB` or in my case `en-DE`

I will attach some of the things i tried, and a possible workaround.
<details>
  <summary>Click to expand!</summary>

```py
import locale

locale.getlocale()
#Traceback (most recent call last):
#  File "<string>", line 1, in <module>
#  File "C:\Python39\lib\locale.py", line 593, in getlocale
#    return _parse_localename(localename)
#  File "C:\Python39\lib\locale.py", line 501, in _parse_localename
#    raise ValueError('unknown locale: %s' % localename)
# ValueError: unknown locale: en_DE

import time, wx

app = wx.App()

time.strptime('12:00', '%H:%M')
# Traceback (most recent call last):
#   File "<string>", line 1, in <module>
#   File "C:\Python39\lib\_strptime.py", line 268, in <module>
#     _TimeRE_cache = TimeRE()
#   File "C:\Python39\lib\_strptime.py", line 182, in __init__
#     self.locale_time = LocaleTime()
#   File "C:\Python39\lib\_strptime.py", line 69, in __init__
#     self.lang = _getlang()
#   File "C:\Python39\lib\_strptime.py", line 28, in _getlang
#     return locale.getlocale(locale.LC_TIME)
#   File "C:\Python39\lib\locale.py", line 593, in getlocale
#     return _parse_localename(localename)
#   File "C:\Python39\lib\locale.py", line 501, in _parse_localename
#     raise ValueError('unknown locale: %s' % localename)
# ValueError: unknown locale: en_DE
locale.setlocale(locale.LC_ALL, '')
# 'English_Germany.1252'
time.strptime('12:00', '%H:%M')
# time.struct_time(tm_year=1900, tm_mon=1, tm_mday=1, tm_hour=12, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=1, tm_isdst=-1)
```
</details>

**Comment by jeanslack** [comment]
Thanks for reply and the possible workaround,

>  Im sorry, I have no clue what you mean by "PNG cleanup" and the issue you're referring to makes no sense at all. What PNGs would I clean up? What folder? Do you mean the PNGs shipped with videomass?

You're right, I didn't specify. I meant, try deleting the color profile on the videomass.png file located on "C:\Python39\lib\site-packages\videomass3\art\icons", as from your [stacktrace](https://github.com/jeanslack/Videomass/issues/17#issue-816164800) the error occurs on [line 88 of the wizard dialog](https://github.com/jeanslack/Videomass/blob/bb72f77630148f8fcb4c0dd4db0af967fdea4072/videomass3/vdms_dialogs/wizard_dlg.py#L88). 
As an alternative you can comment out lines 88 to 92 and line 111 of the wizard_dlg.py file located on "C:\Python39\lib\site-packages\videomass3\vdms_dialogs\wizard_dlg.py", thus preventing the videomass.png file from loading. Obviously these are just extreme attempts, one of which has an reply here: https://github.com/wxWidgets/Phoenix/issues/769#issuecomment-368715087.

> i have tried running with python 3.7 and i still get the exact same issue.

Ok, now we know

> after some more digging i stumbled across this thread suggesting that locales in windows are just completely broken, as python itself doesn't recognize locales such as en-GB or in my case en-DE

here, this would make my answer above about the videomass.png problem superfluous.

**Comment by laundmo** [comment]
so, interestingly enough after running `exiftool -all= videomass.png` it works.

**Comment by jeanslack** [comment]
That command deletes all meta information from an image. I'll use it to fix this in the next commit.
Thanks for the contribution
