### ISSUE TITLE
ffplay failing on Windows with Fontconfig error

### ISSUE THREAD

**Issue by CComparon** [jeanslack/Videomass#172]
**What operating system are you using?**   
Windows 10

**What version of Videomass are you using and how did you install or run it?**   
latest portable

**Describe the bug**   
Getting error below every time ffplay is spawned by Videomass:
`Fontconfig error: Cannot load default config file: No such file: (null)`

I've got a short PR available to fix the issue: https://github.com/jeanslack/Videomass/pull/171

**Comment by jeanslack** [comment]
@CComparon Thank you very much!
Merged.

Although your PR doesn't completely solve the problem. To fix it completely it is also necessary to change the default strings on the MainFrame: 
https://github.com/jeanslack/Videomass/blob/5600b12caf1249a077b81f08a2c36ce103dfa624/videomass/vdms_main/main_frame.py#L110
https://github.com/jeanslack/Videomass/blob/5600b12caf1249a077b81f08a2c36ce103dfa624/videomass/vdms_main/main_frame.py#L115

I will close this issue as soon as I resolve it with the new pull request.
