### ISSUE TITLE
file name too long

### ISSUE THREAD

**Issue by tissatussa** [jeanslack/Videomass#19]
I just tried to download some video from worldtruthvideos.org and i get this strange error : "File name too long" !

when a Videomass preference would be different, i.e. the file-name-max-length, could this video have been downloaded ?

some more info about his case : using F12 in the browser i see the video is simply embedded by a container, having a normal src attribute : https://worldtruthvideos.org/upload/videos/2021/03/xnQAUnVsrb2jGS89JbtL_04_ab71ca91095ad3dd33f448ba00fb0db5_video.mp4 .. so i think Videomass should be able to download it .. only the file name (derived from the video title) should be truncated !?

It's a bizar exception .. 

URL 1/1 : "https://worldtruthvideos.org/watch/to-me-this-little-white-insect-is-symbolic-of-the-plight-of-white-man-today-making-his-way-in-life-w_NZPWIbgJaWqTOIR.html"
[generic] to-me-this-little-white-insect-is-symbolic-of-the-plight-of-white-man-today-making-his-way-in-life-w_NZPWIbgJaWqTOIR: Requesting header
WARNING: Falling back on generic information extractor.
[generic] to-me-this-little-white-insect-is-symbolic-of-the-plight-of-white-man-today-making-his-way-in-life-w_NZPWIbgJaWqTOIR: Downloading webpage
[generic] to-me-this-little-white-insect-is-symbolic-of-the-plight-of-white-man-today-making-his-way-in-life-w_NZPWIbgJaWqTOIR: Extracting information
[generic] playlist To me, this little white insect is symbolic of the plight of White man, today. Making his way in life with scorn and hate, all around. Avoiding the cracks in his path, set by his many enemies, for fear he will fall in and few people will care enough to save him.: Collected 1 video ids (downloading 1 of them)
ERROR: unable to open for writing: [Errno 36] File name too long: '/home/roelof/Downloads/To_me_this_little_white_insect_is_symbolic_of_the_plight_of_White_man_today._Making_his_way_in_life_with_scorn_and_hate_all_around._Avoiding_the_cracks_in_his_path_set_by_his_many_enemies_for_fear_he_will_fall_in_and_few_people_will_care_enough_to_save_him..mp4.part'
[Videomass]: FAILED !

[Videomass]: completed, but not everything was successful.

---
Roelof Berkepeis
Holland

**Comment by jeanslack** [comment]
hi,

I just successfully downloaded your linked video:  https://worldtruthvideos.org/upload/videos/2021/03/xnQAUnVsrb2jGS89JbtL_04_ab71ca91095ad3dd33f448ba00fb0db5_video.mp4

youtube-dl version: 2021-03-03

Warning: see the URL in your log, you are trying to download a file in html, it should be in mp4.

This is my log:

URL 1/1 : "https://worldtruthvideos.org/upload/videos/2021/03/xnQAUnVsrb2jGS89JbtL_04_ab71ca91095ad3dd33f448ba00fb0db5_video.mp4"
[generic] xnQAUnVsrb2jGS89JbtL_04_ab71ca91095ad3dd33f448ba00fb0db5_video: Requesting header
[download] Destination: /home/blablabla/xnQAUnVsrb2jGS89JbtL_04_ab71ca91095ad3dd33f448ba00fb0db5_video.mp4
[Videomass]: SUCCESS !
Done downloading, now converting ...

[Videomass]: Successfully completed !

**Comment by tissatussa** [comment]
yes, but my issue is different, i wrote the issue a bit confusing .. let me explain : each video on worldtruthvideos.org has an URL with html extension (like https://rumble.com ) and normally the user enters that (html) video URL .. then Videomass indeed finds the concerning embedded mp4 .. but Videomass can not save the file because its name is too long, due to the video title ..

**Comment by jeanslack** [comment]
Sorry, I was not aware of this problem. Seems to be a filesystem limitation (not just Linux) 
See this thread: https://github.com/ytdl-org/youtube-dl/issues/5908

I tried to limit the number of characters for the filename to 100. It seems to work.
I will add this workaround on Videomass to get around this problem.

**Comment by tissatussa** [comment]
I was aware of the filesystem limitation. The 100 char workaround is OK .. i think this issue can be closed.
