### ISSUE TITLE
Unable to wok under user profile with spaces in the name (Windows 10, Videomass 3.3.8)

### ISSUE THREAD

**Issue by bOOT-CoDe** [jeanslack/Videomass#20]
When run in Windows under user with spaces in profile name (made by Windows itself, derived from user name), Videomass 3.3.8 cannot open any folder including configuration folder. Any attempt ended up with two same errors: 'Unable to open folder <drive letter>:\Users\<first part of the profile name>'.
Videomass apparently doesn't works properly with file paths which can by definition contains also whitespaces.

**Comment by jeanslack** [comment]
Hi @bOOT-CoDe, 
are you using the portable version or something?

Can you describe me exactly the operation you were doing? For instance, were you using Presets manager or AV-Conversions? Were you choosing a preset to save a profile? other?

If I understand correctly, you wanted to open the Videomass configuration folder, and using the menu bar [Goto > Configuration directory] gave you this error?

**Comment by bOOT-CoDe** [comment]
Hi @jeanslack.

First I installed the Videomass to folder C:\Programs\Videomass. Later I uninstall it and tried portable version, which I unpack to the same folder, where the installed version previously has resided. Both versions give the same errors.
The error occurs here:
[File > Conversions folder]
[File > Downloads folder]
[Goto > System > Configuration directory]
[Goto > System > Cache directory]

My profile path is "C:\Users\Name Surname". All errors states that the path "C:\Users\Name" cannot be open.
I found out that configuration folder is in all cases created on path "%APPDATA%\videomass" but the Videomass cannot open it.
But if I use [Settings > Preferences] then on the panel [Files Preferences] I see correct folder "C:\Users\Name Surname" in both, Transcodes and Downloads, configuration text boxes.

Today I also found another problem: File paths in configuration file "%APPDATA%\videomass\videomass.conf" are stored in system-wide codepage (Windows use that only for apps doesn't support Unicode) instead of Unicode (e.g. UTF-8 encoding) which leads to troubles when you have to store characters outside codepage. When I set Transcodes folder to something with outside my non-Unicode codepage like to "D:\Videomass\轉碼" and click to OK button, the configuration dialog is not closed but the configuration file "%APPDATA%\videomass\videomass.conf" is crippled. If I then click to Cancel button the configuration file stays crippled. After exit the Videomass I am unable tu run it again. It silently crash without any warning or even window opened. Only deleting the crippled configuration file helps. The same happens when I do similar thing for Download folder.

**Comment by jeanslack** [comment]
> My profile path is "C:\Users\Name Surname". All errors states that the path "C:\Users\Name" cannot be open.
I found out that configuration folder is in all cases created on path "%APPDATA%\videomass" but the Videomass cannot open it.
But if I use [Settings > Preferences] then on the panel [Files Preferences] I see correct folder "C:\Users\Name Surname" in both, Transcodes and Downloads, configuration text boxes.

Thanks for details provided. Now I understand where the path problem occurs when you open the folders above, I will try to fix it.

> Today I also found another problem: File paths in configuration file "%APPDATA%\videomass\videomass.conf" are stored in system-wide codepage (Windows use that only for apps doesn't support Unicode) instead of Unicode (e.g. UTF-8 encoding) which leads to troubles when you have to store characters outside codepage. When I set Transcodes folder to something with outside my non-Unicode codepage like to "D:\Videomass\轉碼" and click to OK button, the configuration dialog is not closed but the configuration file "%APPDATA%\videomass\videomass.conf" is crippled. If I then click to Cancel button the configuration file stays crippled. After exit the Videomass I am unable tu run it again. It silently crash without any warning or even window opened. Only deleting the crippled configuration file helps. The same happens when I do similar thing for Download folder.

Do you think this problem could be solved by adding utf8 encoding for reading or writing? 
example: 
`with open(self.getfileconf, 'w', encoding='utf8') as fconf`

**Comment by bOOT-CoDe** [comment]
> > My profile path is "C:\Users\Name Surname". All errors states that the path "C:\Users\Name" cannot be open.
> > I found out that configuration folder is in all cases created on path "%APPDATA%\videomass" but the Videomass cannot open it.
> > But if I use [Settings > Preferences] then on the panel [Files Preferences] I see correct folder "C:\Users\Name Surname" in both, Transcodes and Downloads, configuration text boxes.
> 
> Thanks for details provided. Now I understand where the path problem occurs when you open the folders above, I will try to fix it.
I think that double quotes around path will helps.

> > Today I also found another problem: File paths in configuration file "%APPDATA%\videomass\videomass.conf" are stored in system-wide codepage (Windows use that only for apps doesn't support Unicode) instead of Unicode (e.g. UTF-8 encoding) which leads to troubles when you have to store characters outside codepage. When I set Transcodes folder to something with outside my non-Unicode codepage like to "D:\Videomass\轉碼" and click to OK button, the configuration dialog is not closed but the configuration file "%APPDATA%\videomass\videomass.conf" is crippled. If I then click to Cancel button the configuration file stays crippled. After exit the Videomass I am unable tu run it again. It silently crash without any warning or even window opened. Only deleting the crippled configuration file helps. The same happens when I do similar thing for Download folder.
> 
> Do you think this problem could be solved by adding utf8 encoding for reading or writing?
> example:
> `with open(self.getfileconf, 'w', encoding='utf8') as fconf`
I am not familiar with the syntax, but it looks like it can helps. The point is that whole file must be in the same Unicode encoding, like utf-8, and it must be always open with the same encoding and all reads and writes must use the encoding.

**Comment by jeanslack** [comment]
Already
