### ISSUE TITLE
probably a me issue

### ISSUE THREAD

**Issue by jay-hd** [jeanslack/Videomass#207]
how do i get the downloads to play back at normal speed. everything i have downloaded is running at 90% speed. like playing a 45 record at 33 speed. this isn't the only app that this has happened with. every app plays back the same. too slow

**Comment by jeanslack** [comment]
Sorry, but I can't figure out how this could happen, as I don't know there are any parameters implemented in the application that could affect the playback speed of the result file you downloaded.
