### ISSUE TITLE
windows exe

### ISSUE THREAD

**Issue by venkat2305** [jeanslack/Videomass#210]
can you please provide .exe file for windows.

**Comment by jeanslack** [comment]
Yes, it's coming, just a little patience

**Comment by venkat2305** [comment]
hey, can you give a installable file instead of a portable one. auto update is not possible with portable versions right?

**Comment by jeanslack** [comment]
The portable version is exactly the same as an installed version, except that the portable version is completely self-contained, while the files of an installed version are moved (installed) to "C:\Program Files" by default. Also, Videomass has never been auto updatable except to update youtube-dl/yt-dlp, but now it is no longer possible to do this either with the portable version or with an installed version.
