### ISSUE TITLE
Always going to Queued Files

### ISSUE THREAD

**Issue by duskull88** [jeanslack/Videomass#212]
## Thanks for taking the time to submit a bug report! Please include the following information:   

**What operating system are you using?**   
Void Linux x86_64

**What version of Videomass are you using and how did you install or run it?**   
4.0.10-x86_64 official AppImage. To be sure that the bug was not introduced in the latest version, I went back and tried a few older versions as well, down to 3.5.8, no difference.

**Describe the bug**   
The initial setup goes fine. After starting the program again, no matter what option I select at the "Welcome to Videomass"
screen, it always goes to "Queued Files" (with the exception of "YouTube Downloader"). I dragged some videos in the "Queued Files" screen, but the button to start the rendering is grayed out. In my shell I see nothing suspicious:

`test@test ~/A/Videomass> ./Videomass-4.0.10-x86_64.AppImage
Info: Embedded on python appimage

(videomass:13767): Gtk-WARNING **: 01:58:57.951: Theme parsing error: gtk.css:2909:9: 'width' is not a valid property name

(videomass:13767): Gtk-WARNING **: 01:58:57.951: Theme parsing error: gtk.css:2916:9: 'width' is not a valid property name
01:58:58 AM: Debug: Adding duplicate image handler for 'Windows bitmap file'
01:58:58 AM: Debug: Adding duplicate animation handler for '1' type
01:58:58 AM: Debug: Adding duplicate animation handler for '2' type` 

Please let me know if you need more info.

**Comment by jeanslack** [comment]
Hello @duskull88 

I don't see any problem in what you described, it seems normal application behavior. Debug messages and also Gtk-WARNING messages printed to the console can be safely ignored.
The [screenshot](https://jeanslack.github.io/Videomass/Pages/User-guide-languages/en/1-User_Interface_Overview_en.pdf) **User Interface Overview** from the official documentation gives an idea of the algorithm used. Even if this documentation is not updated to the latest Videomass release, please read it.

My question is: Could you kindly describe what you would expect by selecting an option in the "Welcome to Videomass"
screen?

PS: It would be interesting to know for the purposes of a possible improvement in the development of the App.

**Comment by duskull88** [comment]
Hello, thanks for your quick reply @jeanslack ,

I took a look at the documentation before openings this issue, that's why I was wondering why I cannot access any profile options. Looking at the **User Interface Overview** PDF now, on page 6 it is shown what the UI for profile options looks like, but I don't have that. To clarify again, from I understand from the documentation, every button on the welcome screen takes you to a different view, that's why there are 6 buttons, right? Or maybe I'm dump 😀 ? I'm willing to record a short video if that would help.

**Comment by jeanslack** [comment]
>  To clarify again, from I understand from the documentation, every button on the welcome screen takes you to a different view, that's why there are 6 buttons, right?

No, it always takes you to the Queued Files panel first (not for YouTube Downloader of course), then clicking the "next" button will take you to a different view.

> I'm willing to record a short video if that would help.

Of course, it could clarify the situation better.

**Comment by duskull88** [comment]
Ah so it was the next button that I was completely ignoring! I'm sorry, now I've tested it and it works perfectly.
