### ISSUE TITLE
Trash folder settings v4.0.10?

### ISSUE THREAD

**Issue by johannesdedoper** [jeanslack/Videomass#215]
Hello @jeanslack,

I'm still using Videomass everyday and very happy with it.
I just downloaded the Appimage v4.0.10 and I was wondering:

Were can I set the folder as being the "trash folder". This was possible in version 4.01?
I tried setting in the folder in config/settings.json to  "trashfolder": "/media/user/DRIVE_D/trash" but it still puts all encoded source files in the ~/.config/videomass/Trash folder

Thanks for all your work!!!!
cheers,
J.

**Comment by jeanslack** [comment]
Hello @johannesdedoper,

Glad to hear from you again.

Well, that feature has been removed to avoid confusion and to be able to centralize the removed files only in a single trash folder.
Was that function so vital to you?

**Comment by johannesdedoper** [comment]
Hi, thnx for replying so quick.
This feature is somewhat vital to me as the Videomass folder is on a small  drive, I have dedicated big drive just for the encoded source files. It doesn't necessarily have to be in the GUI. If I can set it in de settings file that would be fine.

Thnx in advance,
Ciao
J.

**Comment by johannesdedoper** [comment]
You're the BEST!
thnx again ;)

ciao,
J.
