### ISSUE TITLE
[Feature Request] Aria2 support for yt-dlp to accelerate download speed

### ISSUE THREAD

**Issue by samarthshrivas** [jeanslack/Videomass#218]
aria2 can accelerate download speed, its multi threaded, it would be nice addition to give option to set no of threads preferences

**Comment by jeanslack** [comment]
Hello @samarthshrivas 

Do you have any usage examples to use with the yt_dlp API?
I've been doing a search but haven't found much...

Pull Requests are welcome.

**Comment by samarthshrivas** [comment]
Hello @jeanslack 

I have a cli command that i use:
```
yt-dlp -q --external-downloader aria2c --external-downloader-args "-j 50 -s 3 -x 2" https://www.youtube.com/watch?v=CVsbTCdTyAM
```
_'c' in aria2c in not a mistake_


Make sure you have aira2 installed:
```sudo apt install aria2```



Docs for a aria2c:
https://aria2.github.io/manual/en/html/aria2c.html

_I will try to do more research and contribute to this proj after 12 Apr. i have a exam on 11._

**Comment by jeanslack** [comment]
Thanks for your time.
Some considerations: Videomass doesn't execute yt-dlp command line in sub-process to perform download operations, instead it uses [yt_dlp API](https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp), ie Python module.

The following is the list of all options callable using the Python module: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L184

> I will try to do more research and contribute to this proj after 12 Apr. i have a exam on 11.

It's OK no problem

**Comment by samarthshrivas** [comment]
I updated ydl_downloader.py and preferences.py. but i don't know to map these to each other maybe you can help me.

**Comment by jeanslack** [comment]
Hello @samarthshrivas 

Yes, certainly!
Thanks so much, I'll get back to you from there.
