### ISSUE TITLE
[DOWNLOADER GUI] Unable to add title of the Podcast.

### ISSUE THREAD

**Issue by Treadspear** [jeanslack/Videomass#220]
## Thanks for taking the time to submit a bug report! Please include the following information:   

**What operating system are you using?**   
WINDOWS 1O ENTERPRISE LTSC

**What version of Videomass are you using and how did you install or run it?**   
The version of the program you used and how you installed or ran it, for example: via pip install, running AppImage, running from source code, installing from an installer, etc.   

EXTRACTED
4.0.10_x86_64-portable
ADMINISTRATIVE MODE

**Describe the bug**   

Hello I  managed to download a podcast using this link:
- https://www.globalplayer.com/podcasts/episodes/7Drf561/

Success using these options: 
- Precompiled Videos
- Download by Format Code
 [All other options did not work for me]

The file downloaded were named:
- Steve_Allen_-_The_Whole_Show_-_Podcast_Global_Player.f0.mp3
- Steve Allen - The Whole Show - Podcast ｜ Global Player-LBC-UK.mp3

Title of this podcast episode I would like it to included is:
- Flat Cap

I am not sure how to include the episode title to the download, however it seems they have managed to do this on the other ytdl post I made: https://github.com/ytdl-org/youtube-dl/issues/31688#issue-1599472550

Hope anyone help, let me know if you're unsure what I'm talking about and need more information lol

Thank you

**Comment by jeanslack** [comment]
Hello @Treadspear 

If I understand correctly, you are not satisfied with the titles of the podcast you downloaded, and therefore you would like to change them to flat cap? but what do you mean by flat cap?

Second, have you tried toggling the "Restrict file names" checkbox on the options pane?

**Comment by Treadspear** [comment]
Flat Cap is the name of this podcast episode i downloaded. and yes i have tried that. on the website it shows "Flat Cap Steve Allen - The Whole Show"

**Comment by jeanslack** [comment]
Ah OK sorry for the misunderstanding. 

So, I inform you that Videomass is now totally based on **yt-dlp** and no longer on **youtube-dl.** If you want to get more information why the downloaded title is different from the website one, this is the yt-dlp page: https://github.com/yt-dlp/yt-dlp

They are very helpful and specialize in this kind of thing. In the meantime, I'll leave this issue open if you want further clarification.

**Comment by jeanslack** [comment]
Closed due to inactivity
