### ISSUE TITLE
AppImage ERROR: No module named 'yt_dlp'

### ISSUE THREAD

**Issue by thorpedo895** [jeanslack/Videomass#225]
## Thanks for taking the time to submit a bug report! Please include the following information:   

**What operating system are you using?**   
Kubuntu 22.10 Plasma 5.27.4

**What version of Videomass are you using and how did you install or run it?**   
Running AppImage 5.0.0

**Describe the bug**   

The AppImage version has an error when running, it says ERROR: No module named 'yt_dlp' but I have the latest version of yt-dlp installed on my system. When I run Videomass 5.0.0 from the source code, it runs without any errors. I would appreciate if you could solve this minor inconvenience. Thank you.

![Screenshot_20230416_173307](https://user-images.githubusercontent.com/34789460/232343883-9f8c48c8-351d-4ab4-aad9-37158053849d.png)

**Comment by jeanslack** [comment]
Hello @thorpedo895 

I'm sorry, I forgot to take some precautions to be able to install yt-dlp correctly in the AppImage.
Next week I should release the new version of Videomass which will fix the problem.

**Comment by thorpedo895** [comment]
Thank you very much for responding so quickly and for all the effort you make, it is greatly appreciated. I will wait for the new version then.

**Comment by jeanslack** [comment]
The new version has been released. 
Thank you for appreciation.
