### ISSUE TITLE
No Dark Mode for Windows

### ISSUE THREAD

**Issue by bitsky6** [jeanslack/Videomass#23]
Is there a way to have the UI in Dark Mode in Windows just like in Mac?

Thanks

**Comment by bitsky6** [comment]
Thanks

----------------------------------------
László Pető
IT & AV Specialist
Live Sound Engineer
Broadcasting Specialist
Entertainment Technical Manager
[cid:ii_ab086ba0baa24a35][cid:ii_0cd3013123af4019]
[cid:ii_ed58f50073904395][cid:ii_afc939b7b1fc47da]
[cid:ii_88efb08f08b54c7f]

AMX DESIGN (Video and Control)
AMX TECHNICIAN (Enova)
AMX TECHNICIAN (Networked AV)
On Apr 30, 2021, at 21:01, Gianluca Pernigotto ***@***.******@***.***>> wrote:

hi,

I will take some time to investigate. I'll let you know as soon as possible.

**Comment by jeanslack** [comment]
Hi,

This seems to be a problem that affects the applications developed on the [Win32 API](https://docs.microsoft.com/en-us/windows/win32/) (such as Notepad, Wordpad, MSPaint) also used to implement the MSW port of wxWidget and therefore also of wxPython on which Videomass is based. 

Dark Mode can only effect on [UWP](https://docs.microsoft.com/en-us/windows/uwp/)/WinRT/WinUI apps and currently there is no possibility to use it from Win32, but MS did advertise that the upcoming [WinUI 3.0](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md) will include easy access to new features from win32 apps.

Resources: 
https://forums.wxwidgets.org/viewtopic.php?t=45869
https://forums.wxwidgets.org/viewtopic.php?t=47110

**Comment by bitsky6** [comment]
Well then will wait for the update.
Thanks
