### ISSUE TITLE
NVIDIA hardware acceleration

### ISSUE THREAD

**Issue by robouden** [jeanslack/Videomass#236]
## Thanks for taking the time to ask a question!
Wondering how to make a preset with Videomass and NVIDIA RTX3070 hardware to speed up the encoding. Any suggestions welcomed.

Regards,
rob Oudendijk

**Comment by jeanslack** [comment]
Hello @robouden 

Have you looked at the [NVidia Accelerated Video Coding](https://github.com/jeanslack/Videomass-presets/tree/master/NVidia%20accelerated%20video%20encoding) presets?
You may also find useful information on the [FFmpeg wiki](https://trac.ffmpeg.org/wiki/HWAccelIntro).

I hope these links are useful to you. I can't give you any more info because I don't use hardware acceleration.

**Comment by johannesdedoper** [comment]
Try something like this:

`-vcodec hevc_nvenc -b:v 2000k -preset fast -c:a aac -b:a 128k -c:s copy`
(video-encoding to H265 using NVENC, bitrate video set on 2000kb and preset fast, audio encoding to aac at 128kb, copying all subtitles if any present.)

`-vcodec hevc_nvenc -cq 23 -preset medium -c:a aac -c:s copy `
(video-encoding to H265 using NVENC, Constant quality setting on 23 and preset medium, audio encoding to aac best quality, copying all subtitles if any present.)

Go to presets -> click on "ADD" en copy-paste one of the above in the "One pass" window. Type in "mkv" for the file output format.
Ready to go.

Cheers, 
J.

**Comment by robouden** [comment]
J,

Yess!!! That worked after I install the nvidia-uvm-init.sh script from
https://matthieu.yiptong.ca/tag/plex/


Regards,
Rob Oudendijk

**Comment by johannesdedoper** [comment]
Great! Nice to hear.

This video encoder is the best and has features no other encoder has.
Also the tool has a great developer who is very involved and open to useful changes! 

Have fun encoding. 
Groetjes ;)
 J.

**Comment by robouden** [comment]
J,

Would be nice if I could get the same acceleration for VP8 or VP9 and
export to webm. You know if that’s possible?

Regards,
Rob Oudendijk

**Comment by jeanslack** [comment]
> Try something like this:
> 
> `-vcodec hevc_nvenc -b:v 2000k -preset fast -c:a aac -b:a 128k -c:s copy` (video-encoding to H265 using NVENC, bitrate video set on 2000kb and preset fast, audio encoding to aac at 128kb, copying all subtitles if any present.)
> 
> `-vcodec hevc_nvenc -cq 23 -preset medium -c:a aac -c:s copy ` (video-encoding to H265 using NVENC, Constant quality setting on 23 and preset medium, audio encoding to aac best quality, copying all subtitles if any present.)
> 
> Go to presets -> click on "ADD" en copy-paste one of the above in the "One pass" window. Type in "mkv" for the file output format. Ready to go.
> 
> Cheers, J.

@johannesdedoper 
Could it be helpful if I add these presets to the ones you've already created? Or create new ones?

**Comment by johannesdedoper** [comment]
@jeanslack Sure, will send you my new list of presets in a few days.

@robouden Why use VP9? But if you want to you can use something like this:
`-vcodec libvpx-vp9 -b:v 2000k -preset fast -c:a libvorbis -b:a 128k -c:s copy`
Put as extension "webm"
However this is not hardware accelerated (runs about 1:1 when encoding). 
I would not know how hardware accelerate vp9 within ffmpeg.

Cheers all.
J.

**Comment by robouden** [comment]
J,

Thanks for the fast replies. I was just impressed with the speed of the hardware acceleration. But I really wanted a fast way to get a small in file size and reasonable quality webm formatted video file. What would be your suggestion?

Regards,
rob

**Comment by robouden** [comment]
J,

Very interesting  information, I will dig into it later.
So much to learn.. BTW.. Great program you made.. :)

Regards,
rob

**Comment by johannesdedoper** [comment]
I would always go for h265/x265 as it's hardware accelerated, good quality per MB and widely accepted.
Therefore I convert all files to h265 in a mkv container as this accepts multiple (audio and video) streams en multiple subtitles. 

BTW, this great little program is developed by Jeanslack, not me :)
I'm just a great fan of him and his program!
You can do much more with this great program, e.g. conversion of the audio only, normailzation of the audio only, or ripping the audio to a wav/mp3 file etc. without touching the video. You can also select streams (e.g. one of the 2 audio languages embedded in one video file) to convert.

I attached all my personal encoder settings to try.
Just unpack and put it the Videomass preset folder.
Cheers,
J.

[-h265videomass.prst.zip](https://github.com/jeanslack/Videomass/files/11787718/-h265videomass.prst.zip)

**Comment by jeanslack** [comment]
Thanks a lot Johannes! 
I will update the [Videomass-presets](https://github.com/jeanslack/Videomass-presets) repo with your presets.

**Comment by johannesdedoper** [comment]
@jeanslack : You're are very welcome.

These are my own personal presets so there is a sort of overlap in presets but with minor tweaks. E.g. tweaked for copying one specific subtitle stream or different bit-rates, quality settings, with audio normalization or not etc.  
So maybe too much?

cheers.
J.

**Comment by jeanslack** [comment]
I'll take a look at it then I'll make a selection based on what I think will be useful for some users. In any case these presets will not be part of those normally distributed with Videomass, but will be available as additional optional presets for specific use cases.
Anyway thanks again!

Ciao

**Comment by robouden** [comment]
I made a preset for converting MP4 files to MOV files (without getting a lot bigger) on a Linux system to be used in Davinci Resolve. Can I share that preset here?

Regards,
Rob

**Comment by jeanslack** [comment]
@robouden  

Sure!

If you think it could potentially be useful to someone, we could add it to the presets repo https://github.com/jeanslack/Videomass-presets.

In the future, if you want to share other presets, it would be better to send them directly to that repo.

Thank you!

**Comment by johannesdedoper** [comment]
@jeanslack I will. thnks.

Cheers,
J.
