### ISSUE TITLE
[Suggestion] Add an option to download auto generated subtitles

### ISSUE THREAD

**Issue by akonon** [jeanslack/Videomass#240]
There is a yt-dlp command line option to download auto subs:
`--write-auto-subs`

Would be great to have it in the Videomass gui.

**Comment by jeanslack** [comment]
Hi @akonon 
I'll see what I can do, thanks for the suggestion.

**Comment by akonon** [comment]
Thank you @jeanslack 
I also use `--sub-langs` with `--write-auto-subs` to limit downloads, as there can be lots of auto subs (auto translations).

**Comment by jeanslack** [comment]
Yes, my idea is to implement a specific editor for subtitles (which can be called from a button in the options column) which includes the possibility of choosing subtitles and preferred languages.
This way I could minimize the length of the options column on the UI.
