### ISSUE TITLE
not using yt-dlp proxy setup?

### ISSUE THREAD

**Issue by LeisureLinux** [jeanslack/Videomass#246]
~ ᐅ uname -a
Linux debian-01 6.3.0-7-generic #7-Ubuntu SMP PREEMPT_DYNAMIC Thu Jun  8 16:02:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

~ ᐅ yt-dlp --version                                                         
2023.07.06

~ ᐅ cat ~/.config/yt-dlp/config
#
  --proxy http://192.168.6.166:8888/

As above, I can use yt-dlp in terminal without specify the proxy url in command line. 
But when in GUI videomass, it call yt-dlp, is not using the proxy url in config file. 

Is it a bug?

**Comment by jeanslack** [comment]
Sorry for the late reply.

No, it is the default behavior of yt-dlp when used as a Python module. So if you use yt-dlp from the command line it will be able to read its configuration file, not if you use its Python module.
So to have a certain feature (for example use a proxy), it must first be implemented in the Videomass GUI.

**Comment by LeisureLinux** [comment]
so the GUI Interface Proxy Configuration is a new feature waiting to be implemented?

**Comment by LeisureLinux** [comment]
For now, only use proxychains to call the AppImage will work in Linux if have to use a proxy.

**Comment by jeanslack** [comment]
> so the GUI Interface Proxy Configuration is a new feature waiting to be implemented?

Exactly, but since tools like proxychains exist, the priority of this feature is secondary for now.

**Comment by jeanslack** [comment]
Hi @LeisureLinux , 
I'm trying to implement the ability to use a proxy on Videomass. But I would also need your help to test how it works. Would you be willing to collaborate to make this implementation possible?
