### ISSUE TITLE
Adding metadata or embedding a subtitle seems to take an excessive amount of time? 

### ISSUE THREAD

**Issue by LetsGoOnAnAdventure** [jeanslack/Videomass#247]
Thanks for developing this great tool!! I've noticed some behaviour that might be a bug, or maybe just unfortunate behaviour: 

I am using:
 Windows 10, Ver 22H2, OS build: 19045.3324
 Videomass 5.0.2, installed from an installer

The issue I have noticed is that the time needed to embed metadata or a subtitle seems to take a long time, expecially for longer clips? 
An example - for a 45 min clip, I timed the post-dl fixes to be the following: 
>Done downloading, now converting ...
>[FixupM3u8] Fixing MPEG-TS in MP4 container of ...  (50s)
>[Metadata] Adding metadata to ... (65s)
>[EmbedSubtitle] Embedding subtitles in ... (57s)

For a clip of double the lenght, the fix-times seems to at least double, maybe more (it feels like that :D)

**Comment by jeanslack** [comment]
Sorry for late,
I completely forgot to reply to you.

You were probably using an outdated version of yt-dlp and unfortunately, to solve your problem, Videomass supplied with the Windows installers does not allow you to update yt-dlp.

Currently, although there has been further development of this application and a new release of version v5.0.3, there are no plans to release an installer for Windows or MacOS in the future until I can resolve the issues described [here](https://jeanslack.github.io/Videomass/Pages/Packages/Windows.html#notice-for-mswindows-owners)
and [here](https://github.com/jeanslack/Videomass/issues/165) .

The certainly less problematic alternative with Windows and MacOs is to install Videomass from PyPi, which will allow you to easily perform upgrades for any installed application, including Videomass and yt-dlp.
For further information follow the procedures in these links:   
- https://github.com/jeanslack/Videomass/wiki/Installation-using-pip
- https://packaging.python.org/en/latest/tutorials/installing-packages/

Obviously you will first need to install a sufficiently updated version of Python that can be compatible with wxPython.
For further clarification do not hesitate to contact me.

**Comment by jeanslack** [comment]
Closed due to inactivity
