### ISSUE TITLE
AssertionError "invalid bitmap" in Videomass 5.0.2 -- possible reversion?

### ISSUE THREAD

**Issue by wiloma** [jeanslack/Videomass#248]
## Thanks for taking the time to ask a question!
Hi, I've installed Videomass 5.0.2 using pipx on Debian Sid. When I try to start from Terminal I get the dreaded C++ assertion failed" error. I know this was a problem with versions before 4.0.3. Is it back?

System: 
<code>Videomass: 5.0.2 (released)
Platform: Linux
Version: #1 SMP PREEMPT_DYNAMIC Debian 6.5.8-1 (2023-10-22)
Release: 6.5.0-3-amd64
Architecture: ('64bit', 'ELF')
Python: 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]
wxPython: 4.2.1 gtk3 (phoenix) wxWidgets 3.2.2.1
</code>

Error:
<code>
Info: executable=/home/omar/.local/bin/videomass
Traceback (most recent call last):
  File "/home/omar/.local/pipx/venvs/videomass/lib/python3.11/site-packages/videomass/gui_app.py", line 106, in OnInit
    self.wizard(self.iconset['videomass'])
  File "/home/omar/.local/pipx/venvs/videomass/lib/python3.11/site-packages/videomass/gui_app.py", line 155, in wizard
    main_frame = Wizard(wizardicon)
                 ^^^^^^^^^^^^^^^^^^
  File "/home/omar/.local/pipx/venvs/videomass/lib/python3.11/site-packages/videomass/vdms_dialogs/wizard_dlg.py", line 528, in __init__
    self.pageOne = PageOne(self, icon_videomass)  # start...
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omar/.local/pipx/venvs/videomass/lib/python3.11/site-packages/videomass/vdms_dialogs/wizard_dlg.py", line 70, in __init__
    img = bitmap.ConvertToImage()
          ^^^^^^^^^^^^^^^^^^^^^^^
wx._core.wxAssertionError: C++ assertion ""IsOk()"" failed at /tmp/pip-install-4et7op2m/wxpython_a1d2f35db54144e99a0e718f776de1ee/ext/wxWidgets/src/gtk/bitmap.cpp(800) in ConvertToImage(): invalid bitmap
OnInit returned false, exiting...</code>

**Comment by jeanslack** [comment]
Hi,
Sorry for late, I completely forgot to reply to you.

I'm sorry, but unfortunately, not using Debian Sid, I can't reproduce your problem. But I can assure you that on Debian11 bullseye  (the old stable) and Debian12 bookworm (stable) I have not encountered this problem.
Have you solved it in the meantime?

**Comment by jeanslack** [comment]
Closed due to inactivity

**Comment by wiloma** [comment]
Ahoy Gianluca!

Sorry, you wound up in my junk mail and I just found it. 

I did solve the bitmap problem. I just forget how. Oops. It still shows up on OS X, but that is less surprising.

I'm fine marking it solved.


--Omar
