### ISSUE TITLE
Videomass not portable

### ISSUE THREAD

**Issue by midaspt** [jeanslack/Videomass#25]
I quickly tested **Videomass** current release -- as reported at [www.portablefreeware.com/forums/viewtopic.php?t=25558](https://www.portablefreeware.com/forums/viewtopic.php?t=25558) -- and regret to report that it isn't really portable, at least in Windows.

Thus, if ran out of an USB drive, **Videomass** settings will be left behind after the drive is disconnected and taken elsewhere.

I am hereby requesting a workaround to keep everything inside the program folder (for instance, in an '_appdata_' sub-folder if a parameter is passed at start up or a portable signaling file is found)...

Thanks for your consideration.

**Comment by jeanslack** [comment]
hi @midaspt 
In fact I will have to add a condition on the code in case the application is running as portable. This is to keep the settings separate between the installed and portable version.

Thank you for your suggestion.

**Comment by jeanslack** [comment]
The portable version for Windows should now be really portable. The configuration file and all other user data will be saved in a folder called _**portable_data**_ which will be inside the 'appdata' folder.

Note that some settings such as file destination may cause problems if the portable application is used on multiple PCs, making it necessary to reset some settings.
