### ISSUE TITLE
Update to  the Spanish Translation

### ISSUE THREAD

**Issue by katnatek** [jeanslack/Videomass#250]
Hello, time to not talk with you, sorry I've been busy
Here is the updated Spanish translation, I hope it has a good quality

[videomass.po.txt](https://github.com/jeanslack/Videomass/files/13401466/videomass.po.txt)

Github don't allow to upload .po files, so I add .txt extension
I clean legacy translations in the file

**Comment by jeanslack** [comment]
Hello @katnatek
Thank you so much for your new translation, I just included it in the [master branch](https://github.com/jeanslack/Videomass), all ready!
