### ISSUE TITLE
Presets with hardware acceleration

### ISSUE THREAD

**Issue by dev-johnny-gh** [jeanslack/Videomass#272]
Hi, I'm trying to use Videomass with FFmpeg and make use of hardware acceleration.

So I'm trying to use the preset to input some custom parameters. But I don't know how to input the command on preset.

`ffmpeg -hwaccel qsv -c:v h264_qsv -i /root/.config/videomass/test.mp4 -c:v hevc_qsv out.mp4`

Can you give me a hand on this?

**Comment by jeanslack** [comment]
Hi johnny, welcome!

If I understand correctly, you want to add/edit a new profile of a preset using Videomass?

If so, you need to use the Preset Manager and click on the `Add` or `Edit` buttons and enter the command parameters from there. But you do not have to enter the binary/executable (ffmpeg) or enter the name of the first input file (i.e. the one you should have imported into Videomass)

**Comment by dev-johnny-gh** [comment]
i understand, but the hardware acceleration command is different, you have to input decoder parameter(-hwaccel qsv -c:v h264_qsv) before input file, but i don't know how to do it with presets

ffmpeg -hwaccel qsv -c:v h264_qsv -i /root/.config/videomass/test.mp4

**Comment by dev-johnny-gh** [comment]
if you can add decoder parameter field on preset, and concat it with input file parameter, it would be better.

or you can provide a advance mode for preset, use some placeholders like %ffmpeg, %input, %output, and let the user control the whole command.

**Comment by jeanslack** [comment]
> i understand, but the hardware acceleration command is different, you have to input decoder parameter(-hwaccel qsv -c:v h264_qsv) before input file, but i don't know how to do it with presets
> 
> ffmpeg -hwaccel qsv -c:v h264_qsv -i /root/.config/videomass/test.mp4

Sure, I'm just now implementing this functionality on the Preset Manager, but at the same time I'm also working on other (difficult) implementations and I'll need a few days to complete them.

> if you can add decoder parameter field on preset, and concat it with input file parameter, it would be better.
> 
> or you can provide a advance mode for preset, use some placeholders like %ffmpeg, %input, %output, and let the user control the whole command.

A text field is provided for each coding pass, where it will be possible to add any global parameters positioned before the `-i` flag and the input file.

As soon as I have something ready I'll let you know, and if you're still available you can try them and evaluate them.

Thank you for opening this new issue.

**Comment by dev-johnny-gh** [comment]
thanks for your great work. let me know once you finish it!

**Comment by FFeliziani** [comment]
Hi, I've taken the liberty to create a fix for this for my personal use and pushed it as PR. It's #274

**Comment by jeanslack** [comment]
Hi Federico, 
Thanks!
As soon as I have a moment I'll take a look at it in detail.
See you soon.
