### ISSUE TITLE
Videomass told me to send this as an issue

### ISSUE THREAD

**Issue by LedHat** [jeanslack/Videomass#28]
Done downloading, now converting ...
[ffmpeg] Destination: /home/andreas/Downloads/youtube_musik2/RHINO/playlist/816 - The_B-52_s_-_Love_Shack_Official_Music_Video.mp3
Deleting original file /home/landreas/Downloads/youtube_musik2/RHINO/playlist/816 - The_B-52_s_-_Love_Shack_Official_Music_Video.mp4 (pass -k to keep)
[ffmpeg] Adding thumbnail to "/home/andreas/Downloads/youtube_musik2/RHINO/playlist/816 - The_B-52_s_-_Love_Shack_Official_Music_Video.mp3"
[youtube] YkHP0661TiA: Downloading webpage
[youtube] YkHP0661TiA: Downloading thumbnail ...
[youtube] YkHP0661TiA: Writing thumbnail to: /home/andreas/Downloads/youtube_musik2/RoniaRunable/playlist/817 - Die_Arzte-Zu_Spat.jpg
[download] Destination: /home/andreas/Downloads/youtube_musik2/RoniaRunable/playlist/817 - Die_Arzte-Zu_Spat.mp4
ERROR: giving up after 0 retries
[Videomass]: FAILED !
[youtube] O8XR2z6vOtg: Downloading webpage
WARNING: Unable to download webpage: <urlopen error [Errno -3] Temporärer Fehler bei der Namensauflösung>
[youtube] O8XR2z6vOtg: Downloading API JSON
ERROR: Unable to download API page: <urlopen error [Errno -3] Temporärer Fehler bei der Namensauflösung> (caused by URLError(gaierror(-3, 'Temporärer Fehler bei der Namensauflösung')))
[Videomass]: FAILED !
[youtube] vK2iIjHze2A: Downloading webpage
WARNING: Unable to download webpage: <urlopen error [Errno -3] Temporärer Fehler bei der Namensauflösung>
[youtube] vK2iIjHze2A: Downloading API JSON
ERROR: Unable to download API page: <urlopen error [Errno -3] Temporärer Fehler bei der Namensauflösung> (caused by URLError(gaierror(-3, 'Temporärer Fehler bei der Namensauflösung')))
[Videomass]: FAILED !
[youtube] usf_0kbWACM: Downloading webpage
WARNING: Unable to download webpage: <urlopen error [Errno -3] Temporärer Fehler bei der Namensauflösung>
[youtube] usf_0kbWACM: Downloading API JSON
ERROR: Unable to download API page: <urlopen error [Errno -3] Temporärer Fehler bei der Namensauflösung> (caused by URLError(gaierror(-3, 'Temporärer Fehler bei der Namensauflösung')))
[Videomass]: FAILED !
[youtube] m97WlpsuU74: Downloading webpage
WARNING: Unable to download webpage: <urlopen error [Errno -3] Temporärer Fehler bei der Namensauflösung>
[youtube] m97WlpsuU74: Downloading API JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[Videomass]: FAILED !

**Comment by jeanslack** [comment]
hi @LedHat 

This is not a Videomass problem but youtube_dl. 
Which version of youtube_dl are you using with Videomass? because you are probably using an older version of youtube_dl.
The latest version today is 2021.06.06.

**Comment by LedHat** [comment]
It tells me : "You are using youtube-dl version 2021.06.06"   I downloaded Videomass only a couple days ago.... Just another question, is it possible to download videos from a Playlist but starting at a certain point. I know that this feature exists in youtube-dl but not quite sure if it`s implemented in Videomass.

**Comment by jeanslack** [comment]
> It tells me : "You are using youtube-dl version 2021.06.06" I downloaded Videomass only a couple days ago....

Weird, I just tried to download one of those videos and had no problems. 
![Screenshot_20210802_150946](https://user-images.githubusercontent.com/8676484/127867629-cb928474-914e-4f32-9377-b93b33ab4d16.png)

> Just another question, is it possible to download videos from a Playlist but starting at a certain point. I know that this feature exists in youtube-dl but not quite sure if it`s implemented in Videomass.

No, this feature is not implemented on Videomass, sorry.

**Comment by LedHat** [comment]
All right, maybe just a bug on my pc..
Is it planned to include the indexed download feature?

**Comment by jeanslack** [comment]
Maybe a network problem? maybe links copied incorrectly?
Can you tell me In which OS are you using Videomass and how did you install it please? 

> Is it planned to include the indexed download feature?

Being a very convenient feature I could implement it in the future.

**Comment by LedHat** [comment]
Iam using Ubuntu 20.4, and i installed it i think like the tutorial on github says:
$ sudo add-apt-repository ppa:jeanslack/videomass
$ sudo apt-get update
$ sudo apt install python3-videomass


Network problems are definitely possible. I`d appreceate if the indexing function would get implemented .
Thanks for providing this great peace of software.

**Comment by jeanslack** [comment]
> Iam using Ubuntu 20.4, and i installed it i think like the tutorial on github says:
$ sudo add-apt-repository ppa:jeanslack/videomass
$ sudo apt-get update
$ sudo apt install python3-videomass

All right!

> I`d appreceate if the indexing function would get implemented .
Thanks for providing this great peace of software.

Thanks to you.
