### ISSUE TITLE
Wont abort download

### ISSUE THREAD

**Issue by kolbdog323** [jeanslack/Videomass#300]
I am trying to abort a youtube download in the middle of a download but the abort button is greyed out please fix it since its very annoying having to wait for the video to finish downloading before you can close videomass.

**Comment by jeanslack** [comment]
Sorry, that button will not work for a single download, so it is not activated. 
As explained [here](https://jeanslack.github.io/Videomass/known_problems.html#known-problems-and-solutions) programmatic stopping of a download has not yet been implemented in the [yt_dlp API](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#embedding-yt-dlp) and there is currently no alternative. 

EDIT
After some tests, a new implementation for downloads is planned, being able to run yt-dlp as an executable/binary so it will be possible to stop the download in progress from any point.
