### ISSUE TITLE
Add presets bestaudio, worstvideo, --cookies-from-browser....

### ISSUE THREAD

**Issue by trimechee** [jeanslack/Videomass#305]
Hello, thank you for this awesome efficient downloader ! 💯 🥇

Please i have request : for exemple we hope to download quuckly only audio from youtube videos poscasts, so it will be great to even more speed up and simplify the process of adding presets worstaudio, bestaudio, worstvideo, bestvideo, option to download directly quick medium video resolution, -f worstaudio -x,
-f bestaudio -x, and adding cookies preset if there is problem with dwnloading video from facebook for example.....: --cookies-from-browser firefox....

Thank you so much !

**Comment by jeanslack** [comment]
Hello!
Sorry for late.

As regards cookies, you can set them by clicking on the Options button on the toolbar; go to the Cookies tab where you set what you need.

For the "bestaudio"/"worstaudio" presets using the "Download audio only" option I will see what I can do.

Thanks for the idea!

**Comment by trimechee** [comment]
Awesome !! Thank you so much :) 🥇
