### ISSUE TITLE
No portable executable/ windows installer

### ISSUE THREAD

**Issue by Chaython** [jeanslack/Videomass#310]
The link on the website you link out to is dead, and the past several editions don't have the windows versions only the .deb listed?
I'd be fine with using the python edition if only Windows environmental variables actually worked ;'(

https://github.com/jeanslack/Videomass/releases/download/v5.0.2/Videomass-v5.0.2_x86_64-portable.7z is the working link for the latest windows portable version. In your website you link to https://github.com/jeanslack/Videomass/releases/download/v5.0.12/Videomass-v5.0.2_x86_64-portable.7z, which evidently doesn't exist.

**Comment by Chaython** [comment]
Rather than linking to your site, then linking back to github and manually updating your site, you could recommend deploying via powershell, this is an adaption of my brave portable updater script which downloads and extracts the package

Rather than linking to your site, then linking back to github and manually updating your site, you could recommend deploying via powershell, this is an adaption of my brave portable updater script to download the .7z
```

# Set the owner and repository
$owner = "jeanslack"
$repo = "Videomass"

# Set the URL for the releases
$url = "https://api.github.com/repos/$owner/$repo/releases"

# Get the releases information
$response = Invoke-RestMethod -Uri $url
$releases = $response

# Find the most recent release with the required asset
$latestRelease = $null
foreach ($release in $releases) {
    foreach ($a in $release.assets) {
        if ($a.name.EndsWith("win32-x64.zip")) {
            $latestRelease = $release
            break
        }
    }
    if ($latestRelease -ne $null) {
        break
    }
}

if ($latestRelease -ne $null) {
    # Find the asset with a name ending in portable.7z
    $asset = $null
    foreach ($a in $latestRelease.assets) {
        if ($a.name.EndsWith("portable.7z")) {
            $asset = $a
            break
        }
    }

    if ($asset -ne $null) {
        # Get the download URL for the asset
        $downloadUrl = $asset.browser_download_url

        # Download the asset
        Write-Host "Downloading asset..."
        $response = Invoke-WebRequest -Uri $downloadUrl

        # Save the asset to a file
        $filename = [System.IO.Path]::GetFileName($downloadUrl)
        [System.IO.File]::WriteAllBytes($filename, $response.Content)

        Write-Host "Download completed successfully"
    } else {
        Write-Host "Asset not found"
    }
} else {
    Write-Host "No releases found"
}
```

**Comment by jeanslack** [comment]
Sorry, you're right, I'll take a look at it later.
Thanks for the report.

UPDATE
The portable version of Videomass updated to the latest version is now included. 
The link to the 7z archive is now working too.
I hope everything goes well.

> I'd be fine with using the python edition if only Windows environmental variables actually worked ;'(

Do you mean the Python environment variables or the videomass.exe executable installed via pip?
