### ISSUE TITLE
Making a new preset is cumbersome/buggy

### ISSUE THREAD

**Issue by Column01** [jeanslack/Videomass#316]
## Thanks for taking the time to submit a bug report! Please include the following information:   

**What operating system are you using?** 
Windows 10 22H2 19045.4412

**What version of Videomass are you using and how did you install or run it?**   
`5.0.13` installed via pypi

**Describe the bug**   
When creating a preset for converting videos, it opens a file picker dialogue when you click "Save Preset" but this opened file picker is not a "Create a new file" dialogue, it's a "choose an existing file" dialogue. This means that if you want to save your preset you need to manually create a file, rename it to have the `.prst` extension and then click the button to open that new file. This is silly and cumbersome. On top of that, when I did fill in the info in the newly created file using the popup window (name and description), clicking "Ok" did nothing

**Comment by jeanslack** [comment]
> When creating a preset for converting videos, it opens a file picker dialogue when you click "Save Preset" but this opened file picker is not a "Create a new file" dialogue, it's a "choose an existing file" dialogue.

It's an old implementation that involves saving the profile on an existing preset and not creating a new file. I'm planning to replace it it with a choice dialog with the following options:
- save the profile to an existing preset 
- save the profile to a new preset

> This means that if you want to save your preset you need to manually create a file, rename it to have the .prst extension and then click the button to open that new file. This is silly and cumbersome. 

No, you don't have to create anything manually. If you want to create a pre-formatted blank preset go to Presets Manager and create it from there.
Moreover, as of Videomass version 5.0.6, the current extension/format for presets is `.json` now not `.prst`.

> On top of that, when I did fill in the info in the newly created file using the popup window (name and description), clicking "Ok" did nothing

What do you mean nothing happens? Does the "Successful storing" message not appear after saving the profile on the popup window (name and description) ?

**Comment by jeanslack** [comment]
closed due to inactivity

**Comment by Column01** [comment]
> What do you mean nothing happens? Does the "Successful storing" message not appear after saving the profile on the popup window (name and description) ?

When you click OK, literally as I said, nothing happens. The window remains open, no message is displayed and it just remains as it was. It was also a holiday weekend in my country so sorry for not getting back to you

**Comment by jeanslack** [comment]
Don't worry, I have already fixed the bugs you reported, see #318 

The preset you created manually probably had errors. This is why you shouldn't create presets manually if you don't know how they should be coded.
