### ISSUE TITLE
Totally missing Presets Manager Panel

### ISSUE THREAD

**Issue by HattonLe** [jeanslack/Videomass#317]
Ubuntu 22.04.4 LTS.

Just installed Videomass 6.0.13.

Clicking on "Presets Manager" button doesn't show the manager presets panel... instead it just shows the File List panel, as per the AV Conversions button.

**Comment by HattonLe** [comment]
In fact all buttons apart from the "YouTube Downloader" button display the "File List" panel.

**Comment by jeanslack** [comment]
Hello,

Videomass 6.0.13. ? You would say Videomass 5.0.13, which is the latest version available now.

I don't think there are any bugs from what you described. "File List" panel is always shown as an interface for dragging and dropping files but not for YouTube Downloader of course. 
Check out the documentation: https://jeanslack.github.io/Videomass/User-guide/User_Interface_Overview_en.pdf
To get an idea, look for the «Generic diagram of the functions» heading.

**Comment by HattonLe** [comment]
Hi,

Apologies.. the version is displayed in grey text so dim it would make a ferret blind.

Its 5.0.13.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by HattonLe** [comment]
Your missing the point....

Clicking on the "Presets Manager" button should bring up the presets manager panel.
It doesn't!

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by jeanslack** [comment]
Clicking on that button will not immediately display the Presets Manager but the File List panel. To view the Presets Manager you will then need to click on the "Next" button on the toolbar.

**Comment by HattonLe** [comment]
Face palm on that one.

I think that should be put into the user guide as there wasn't any mention of pressing next in the how to use videomass document I read.

You can mark this as closed.

Thanks.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by jeanslack** [comment]
No problem, it's more important that things are clear now.
I will update the user guide with this information.

> Apologies.. the version is displayed in grey text so dim it would make a ferret blind.

Can you take a screenshot please? Not using Ubuntu I wish I could understand this problem to try to improve it.

**Comment by HattonLe** [comment]
Hi,

Please find attached screenshot of dim version text.

Its very small\thin and hard to read considering there is plenty of empty screen space available.

The document I was working from was
https://jeanslack.github.io/Videomass/User-guide/User_Interface_Overview_en.pdf

Page 5, Clicking one of the buttons will take you to a specific operation.... but it doesn't also say you need to click the Next button for the presets panel.
whereas, clicking the youtube button goes straight to the youtube panel.

Hope that helps.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by jeanslack** [comment]
I don't see any attachments here. Maybe github doesn't support email attachments. You can drag the screenshot directly here if you want.

> Page 5, Clicking one of the buttons will take you to a specific operation.... but it doesn't also say you need to click the Next button for the presets panel.
whereas, clicking the youtube button goes straight to the youtube panel.

Thanks, I'm already working on it
