### ISSUE TITLE
3.4.5 download links 404 for windows and mac

### ISSUE THREAD

**Issue by lxne** [jeanslack/Videomass#33]
The download links for version 3.4.5 both windows and mac end on a 404 page.

**Comment by jeanslack** [comment]
Hi,
Now works?
I uploaded  Videomass-3.4.5-x86_64.AppImage, Videomass-v3.4.5-x86_64-portable.7z and Videomass-v3.4.5-x86_64.dmg.
missing  Videomass-v3.4.5-x86_64-Setup.exe.

**Comment by lxne** [comment]
Thank you.
I leave it open because of videomass.exe download not working.

**Comment by lxne** [comment]
Ups. Still an issue with videomass.exe
dmg and 7z are working.

**Comment by jeanslack** [comment]
Ready, just uploaded.
