### ISSUE TITLE
PPA version for Ubuntu 22.04.4 seems broken

### ISSUE THREAD

**Issue by invicta-nz** [jeanslack/Videomass#332]
## Thanks for taking the time to submit a bug report! Please include the following information:   

**What operating system are you using?**   
22.04.4

**What version of Videomass are you using and how did you install or run it?**   
Followed these steps:

> 
> To install Videomass add this [PPA](https://launchpad.net/~jeanslack/+archive/ubuntu/videomass) to your system:
> 
> $ sudo apt-add-repository ppa:jeanslack/videomass
> $ sudo apt-get update
> $ sudo apt install python3-videomass
> 

**Describe the bug**   
All options on home page take to you the File list. From here you can add files and nothing else. You can't setup presets, you can't concat files, nothing. 

So go to home and choose preset manager. Takes you to file list where you can only add files and nothing else

Choose concatenate files. Takes you to file list where you can only add files and nothing else

Every other option except youtube downloader is the same. Run and other options are always grey'ed out 

"Go" menu has everything grey'ed out except youtube downloader

**Comment by invicta-nz** [comment]
Installed via pip and all was the same. Either I really don't understand how the gui works or there is something broken with this version of Ubuntu

**Comment by jeanslack** [comment]
Hi,

Seems to be the same non-issue described here #317 .
Can you confirm this?

Also, I tried Videomass on Ubuntu 24.04 and no problems appeared.

**Comment by invicta-nz** [comment]
Yes, would agree that it is the same non-issue. Part of the confusion is that on my dark mode setup the difference between greyed out and non is very subtle. So it isn't apparent that the next button is active. Also needing to select files before entering what seems to be a settings page isn't intuitive. 

The other issue of every option being greyed out on the "go" menu tab does seem to be real though.

**Comment by jeanslack** [comment]
OK thanks.

>  Part of the confusion is that on my dark mode setup the difference between greyed out and non is very subtle. So it isn't apparent that the next button is active.

Consider setting an icon theme suitable for dark mode: `Preferences -> Look and Language -> Videomass-dark` or `Ubuntu-Dark-Aubergine` should be optimal for dark themes.

> Also needing to select files before entering what seems to be a settings page isn't intuitive.

Usually when you import files one is automatically selected. That is just a precaution to take into consideration, even if in any case you would be notified by a message.

> The other issue of every option being greyed out on the "go" menu tab does seem to be real though.

For this I will see what I can do.

**Comment by invicta-nz** [comment]
Cool. Thanks for the help. Will close this issue and open up one specific to the "go" menu
