### ISSUE TITLE
exe file flagged as Suspicious but pip install works

### ISSUE THREAD

**Issue by MonsterSe7en** [jeanslack/Videomass#351]
## Thanks for taking the time to submit a bug report! Please include the following information:   

**What operating system are you using?**   
Name and version of the operating system you were using when you encountered the bug   
Windows 11 Version 2382 (0S Build 22631.3880)

**What version of Videomass are you using and how did you install or run it?**   
The version of the program you used and how you installed or ran it, for example: via pip install, running AppImage, running from source code, installing from an installer, etc.   
via the portable exe file downloaded from Github
Videomass 5.0.16

**Describe the bug**   
Flagged by Avast

I just ran the exe file. completed the setup > Ran Auto-detection (Detected ffmpeg) > Enabled GUI for yt-dlp > The software asks for a restart and nothing happens. 

Manually Restarted PC and I open the exe file. Back to the wizard asking me to auto-detect ffmpeg

File was automatically detected and sent to threat labs by Avast

File sent to Threat Labs
The file Videomass.exe was sent to
Threat Labs for analysis - 
Jul 17, 2024, 02:43 PM

![image](https://github.com/user-attachments/assets/1269b8cc-0b53-40c2-9ef2-c989f77d63e3)

Also sharing the link to VirusTotal inspecting the VideoMass.exe file

https://www.virustotal.com/gui/file/72bcaefaac1879a8b8d710635b0a8c2199c4f6b16b8e72eca15d04e180b48c5d

![image](https://github.com/user-attachments/assets/49e3da23-e475-42ed-aced-66fc188ff248)

## Workaround

But 
> [!NOTE]
> > pip install videomass
> Saved the day!!

Avast did complain at first and videomass gave an icon was missing error message once. I've opened the app since, multiple times but haven't encountered the issue. (Since that one time when I first launched videomass)

I do understand that this is an issue that's been ongoing since 2021
I do request you to release the exe files though (People should still be able to add the folder location as an exception in their respective antivirus programs)

# Thank you
And sir. I want to thank you for taking the time to develop this program. It's super useful

Would be useful if you could add an option to add an album art (An image) to audio files. I had to make a batch script to do it.

**Comment by jeanslack** [comment]
HI,

You were right to report this to your antivirus vendor. It's the only way to solve this problem.

> I do request you to release the exe files though (People should still be able to add the folder location as an exception in their respective antivirus programs)

What do you mean? When you unzip the 7zip file you should find the videomass.exe file inside.

**Comment by MonsterSe7en** [comment]
Yes.... It's there... No issues from your end.

I think I read somewhere (in one of the closed issues from 2021) where you expressed your frustration and pondered if you even wanted to release an exe file

I request that you please do release the exe(s) in the future releases as well. As installing via a package manager like pip or Chocolatey can be foreign concept and intimidating to a novice windows user.

Love your code..
Cheers

**Comment by jeanslack** [comment]
I will do my best,

Thank you
