### ISSUE TITLE
Videomass.ico (app icon) path is incorrect

### ISSUE THREAD

**Issue by octocatsup** [jeanslack/Videomass#356]
## Thanks for taking the time to submit a bug report! Please include the following information:   

**What operating system are you using?**   
Windows 11 22H2 (22621.3951)

**What version of Videomass are you using, and how did you install or run it?**   
Installed from [Titus Tech's installer](https://christitus.com/windows-tool/), which uses Chocolatey and WinGet on the backend

**Describe the bug**   
The icon is not pointing to the "art" folder, so the icon is not assigned. I had to go in and manually correct it.

**Comment by jeanslack** [comment]
Hi @octocatsup 

If I'm not mistaken, the version of Videomass available on WinGet is v3.5.8, which is a very outdated version. Can you confirm that the version of Videomass you have installed is that one?

By the way, I didn't know that Videomass was packaged on WinGet.

**Comment by octocatsup** [comment]
Yes, 3.5.8 is correct. See attached.

![image](https://github.com/user-attachments/assets/a17193c5-bad4-44e0-8911-ba659e86f3f3)

**Comment by octocatsup** [comment]
I downloaded the latest version, 5.0.20, from the website, and it's working great.

If anyone uses the same Winget route I did, at least you know about it now!

**Comment by jeanslack** [comment]
Thanks!
