### ISSUE TITLE
Please add instructions to install on mageia 8

### ISSUE THREAD

**Issue by katnatek** [jeanslack/Videomass#36]
## Install on Mageia 8
Exists a third-party repository for Mageia 8 that have a rpm package for videomass.
The repository comes from [BlogDrake](https://blogdrake.net/) The Official Community for Spanish Talking Users

### Instructions
First you have to configure the Official Mageia repositories then

For i586 - 32bit systems
```
su -
urpmi.addmedia --wget --distrib https://ftp.blogdrake.net/mageia/mageia8/i586
urpmi videomass
exit
```
For x86_64 - 64bit systems
```
su -
urpmi.addmedia --wget --distrib https://ftp.blogdrake.net/mageia/mageia8/x86_64
urpmi videomass
exit
```

**Comment by katnatek** [comment]
Note: blogdrake.net is down for the moment but the repository is working

**Comment by jeanslack** [comment]
hi @katnatek, 
I assume the above instructions require admin privileges. If so, is `sudo` or `su` used? I should specify this in the documentation. Sorry but I've never used Mageia. 

Thanks for this great news!

**Comment by katnatek** [comment]
> hi @katnatek,
> I assume the above instructions require admin privileges. If so, is `sudo` or `su` used? I should specify this in the documentation. Sorry but I've never used Mageia.
> 
> Thanks for this great news!

Don't know why don't was showing the 'su -' i edit the instructions and now is there ;)

**Comment by jeanslack** [comment]
...OK
I updated the page like this: https://jeanslack.github.io/Videomass/Pages/Packages/Linux.html#mageia-8

**Comment by katnatek** [comment]
That was fast! :O , thank you!
