### ISSUE TITLE
Option to disable warning message on exit

### ISSUE THREAD

**Issue by smaragdus** [jeanslack/Videomass#39]
Hello,

When exiting [Videomass](https://jeanslack.github.io/Videomass/) it shows a warning message:

`Are you sure you want to exit?`

**screen:**

![Videomass 3 5 0 - 2021-10-08 - 001](https://user-images.githubusercontent.com/9025757/136478455-2a794ce9-2cf6-4908-9eb5-ddc105ba4043.png)

Hitting Enter or clicking Yes is not a big deal but for me it is annoying since when I exit a program I usually want to do it. Also, changing program settings requires to restart the program so I have to hit Enter time and again to exit [Videomass](https://github.com/jeanslack/Videomass) when I need to restart it when I change the settings.

My suggestion, a new check box:

- **Warn on exit**

The check box may be put in **Appearance** tab (**Settings -> Preferences -> Appearance**) and it may be selected by default. I just want to be able to disable this warning message.

Regards

**Comment by jeanslack** [comment]
Hello @smaragdus

> When exiting Videomass it shows a warning message:
Hitting Enter or clicking Yes is not a big deal but for me it is annoying since when I exit a program I usually want to do it.

I agree with you. But it is a convention often used in GUI programs. Anyway, I'll create the option to disable this feature as you suggested.

> changing program settings requires to restart the program so I have to hit Enter time and again to exit Videomass when I need to restart it when I change the settings.


As for restarting the program after changing the settings, I could use a question dialog for a direct exit.

**Comment by smaragdus** [comment]
@jeanslack 

Thanks for the quick response.

> But it is a convention often used in GUI programs. 

Yes it is.

> Anyway, I'll create the option to disable this feature as you suggested.

My usage- any program which allows to disable warning messages on exit in settings- I disable them.

A related question- what about adding a shortcut key for exiting the program? Perhaps either 'Esc' or 'Alt+F4', these seem to be standard commands for 'Exit'. What do you think?

Regards

**Comment by jeanslack** [comment]
> A related question- what about adding a shortcut key for exiting the program? Perhaps either 'Esc' or 'Alt+F4', these seem to be standard commands for 'Exit'. What do you think?

Currently already exists a shortcut key for exiting the program: 'Ctrl+Q'
Can you confirm that shortcut key works on Windows also?
However, all keyboard shortcuts should be listed to the right of each menu item.

**Comment by smaragdus** [comment]
@jeanslack 

> Currently already exists a shortcut key for exiting the program: 'Ctrl+Q'
> Can you confirm that shortcut key work on Windows also?

At least on my machine (Windows 8 x64) 'Ctrl+Q' does not work.

**Comment by jeanslack** [comment]
@smaragdus 

Thanks for reporting it. I will fix it soon.

**Comment by smaragdus** [comment]
![Videomass 3 5 1 - 2021-10-24 - 002](https://user-images.githubusercontent.com/9025757/138574616-3720b461-b74c-44bd-80f4-f7beea55e761.png)

Now for me using the program is a tad more convenient. Thank you!

**Comment by smaragdus** [comment]
I forgot to mention that:

- `CTRL+Q` command

now works on Windows in version [3.5.1](https://github.com/jeanslack/Videomass/releases/tag/v.3.5.1), thanks!
