### ISSUE TITLE
Error if using as temporary destination folder another drive

### ISSUE THREAD

**Issue by rgabbo** [jeanslack/Videomass#41]
If I change the temporary conversion folder in settings tab and I select a folder in my external drive I receive the following error: 

![Immagine](https://user-images.githubusercontent.com/58396985/139589005-c754bd85-56ab-4134-ba35-4fe376ade50c.jpg)

Steps to reproduce:
1) Go to A/V Conversions
2) Select a video file
3) Go to settings tab
4) Choose a folder of an external drive
5) Go to Convert using FFmpeg

**Comment by jeanslack** [comment]
Hello @rgabbo,

What is the version of Videomass you are using?
Are you using the portable edition or the installer?

**Comment by rgabbo** [comment]
Hi. My version is 3.5.1 and I'm using the portable edition.

**Comment by jeanslack** [comment]
This is a bug affecting the portable edition of Videomass. It will be fixed soon. In the meantime you can use the installer which does not have this problem.
Thanks for reporting.

**Comment by jeanslack** [comment]
Fixed
