### ISSUE TITLE
Error 'The program can't start because api-ms-win-core-path-l1-1-0.dll is missing'

### ISSUE THREAD

**Issue by pstein** [jeanslack/Videomass#57]
When I try to start VideoMass I am getting an Error popup

'The program can't start because api-ms-win-core-path-l1-1-0.dll is missing'

Why?

**Comment by jeanslack** [comment]
Hello,

Can you give me some more information please?

- What is your OS and version?
- Which installer did you use and where did you download it from?

**Comment by pstein** [comment]
I am using the portable 64bit VideoMass Version on 64bit Windows 7

Downloaded from:

https://github.com/jeanslack/Videomass/releases

**Comment by jeanslack** [comment]
The executable packages for Windows, i.e the portable version and the one with the installer, were built with Python 3.9 which is not supported on **Windows 7**. The minimum requirement for those packages is **Windows 8.1 64bit**.

However if the command line doesn't scare you, there is another method of installing Videomass on Windows 7, let me know.
