### ISSUE TITLE
Loving this encoder, only missing automatically delete in trashbin after success

### ISSUE THREAD

**Issue by johannesdedoper** [jeanslack/Videomass#66]
Hello, 
I absolutely love this program! 
I already wrote a review on videohelp.com as it was in my opinion not fairly rated.
It would be even more perfect if there is a possibility you would consider to implement an option to automatically delete the encoded file (orginal) to the trashbin (so not permanently) after a successful encoding.
Futhermore and can only say, keep up the excellent work!! and thnx in advance for considering my request.
Bye
Johannes

**Comment by jeanslack** [comment]
Hello @johannesdedoper 
Thank you for your appreciation and also for giving positive feedback on videohelp.com, I just read it now. 
Just to make sure I understand correctly, you want an option that moves the source files (not the processed ones) to the trashbin after a successful transcoding operation. It's correct?

**Comment by johannesdedoper** [comment]
Hello @jeanslack,
thanks for replying.
YES! exactly as you say, because for me, after encoding the source file to another format (h264 to h265) it can be deleted to the trashbin (so not permanently).  
Cheers,
Johannes

**Comment by jeanslack** [comment]
Okay, I'll try to implement this option. The idea is to put a check box on the preferences window that enables or disables this function (default is disabled), or to put this function directly on the file menu so that it can be enabled on demand. What is your opinion about it? Which of the two options can be more comfortable for other users as well?

**Comment by johannesdedoper** [comment]
Nice, thnx in advance.
Ik would place it in the "settings" -> "file preferences" tab.
Attached a picture.
![videomass](https://user-images.githubusercontent.com/100475891/155881344-479c4186-74f7-4c2a-864f-c96c39997250.png)

For me that is the logical place.
But of course it´s your choice.
Kind regards,
J.

BTW: I do not know if you want to use the word recycle bin or trash bin

**Comment by johannesdedoper** [comment]
Hello, it's me again.
I was thinking, would it be interesting if you could choose a directory to put in the source files that are successfully encoded?
So instead of in the trash bin you can choose a folder were these files will be moved. 
Maybe that's more work, than leave it. 
For me it's not important. Either way is great, but maybe other users would like that?
What do you think? 

Cheers, J

**Comment by jeanslack** [comment]
Hello,
I was going to ask you exactly the same thing because it should actually be even easier for me to accomplish this. Furthermore, I could also implement a menu item that opens the file manager directly on the path of the "Videomass Trash". 
It is a good idea for me.

**Comment by johannesdedoper** [comment]
Ok great, I like it!

I was also looking at the text on the videohelp page.
I think this can be more elaborate?
I made a sample text. Of course you are free to use this or edit it:

Videomass is a free, open source and cross-platform GUI for FFmpeg and youtube-dl, concatenate (mux or encode videos), presets manager, conversions. 
This video encoder is userfriendly for beginners and more advanced users. Using the step by step interface (GUI) you can simply choose a preset or make your own. For the people that are familiar with ffmpeg there is the possbility to easily make your own presets using the ffmpeg command line or make a preset through the GUI and adapt this to your specific needs. It offers out of the box output to all possible file formats like MP4, MKV, mov etc. Video: MPEG-4, H.264/AVC, H.265/HEVC, VP9 and audio: AAC, MP3, OPUS, wav FLAC or AC-3 and subtitles and much more! Also you can copy streams (lossless video and/or audio) and extract audio. Finally it has a simple timeline editor, extended multimedia information and optional youtube downloader.

Cheers, 
J.

**Comment by jeanslack** [comment]
Your sample text looks OK, it includes most of the Videomass fetaures. However, if you use that text could you change the ffmpeg name to FFmpeg please?
Thank you for your interest in this program and for wanting to improve the documentation.

**Comment by johannesdedoper** [comment]
Hello,
Glad to help!
But I think you have to contact the admin of videohelp to change the text as you are the developer of videomass.
https://forum.videohelp.com/members/311-Baldrick

If also have more ideas to add/change in the program.
1. The main thing for users that can/will not use the FFmpeg code is to add presets voor NVENC.
If you need to have these tested I can help as I have a Nvidia GPU.
For me this is not a issue as I prefer to make my own presets but I can imagine the average user does want to use the build in presets. 
2. DVD/ISO to mkv (stream/subtitle selection, lossless)

Of course these are only suggestions.
cheers,
J

**Comment by jeanslack** [comment]
> But I think you have to contact the admin of videohelp to change the text as you are the developer of videomass.
https://forum.videohelp.com/members/311-Baldrick

OK

> If also have more ideas to add/change in the program.

Could you open another issue for this topic please?

**Comment by jeanslack** [comment]
### Some remarks about deleting files after encoding
- To solve possible overwriting problems related to move files on same folder (the Trash folder) you need to rename files by adding an identifier and the best identifier in this case is the time and date.
- Also to avoid introducing illegal chars as established by operating system conventions, the time and date format will be like this: `101658-Wed_02_March_2022_filename.extension`
- The location of the Videomass Trash folder will be inside the Videomass configuration folder.

This is the work in progress, what do you think about it?

**Comment by johannesdedoper** [comment]
> ### Some remarks about deleting files after encoding
> 
>     * To solve possible overwriting problems related to move files on same folder (the Trash folder) you need to rename files by adding an identifier and the best identifier in this case is the time and date.
> 
>     * Also to avoid introducing illegal chars as established by operating system conventions, the time and date format will be like this: `101658-Wed_02_March_2022_filename.extension`
> 
>     * The location of the Videomass Trash folder will be inside the Videomass configuration folder.
> 
> 
> This is the work in progress, what do you think about it?

Will it not be possible to choose a folder as a trash folder as the config folder of Videomass is on a small boot drive?
This will be likely the case with other users?

For the rest: Sounds great!
cheers, 
J.

**Comment by jeanslack** [comment]
Yes you are right.
Can you try the source code?

**Comment by johannesdedoper** [comment]
Tried source code and it's working great!! This is fantastic ;)
Maybe there could be a popup before everything is deleted from the trash folder: "are you sure to empty trash folder?" 
cheers,
J.

**Comment by jeanslack** [comment]
OK, closed.
**Notes:**
Files moved to the trash folder are not removed from the "Queued Files" panel as well. Unfortunately it is not possible to do this from another panel. However, if you carry out another encoding process (in the same session) with non-existent files you will be warned by a popup.
