### ISSUE TITLE
[ppa] bionic dependencies

### ISSUE THREAD

**Issue by arrowgent** [jeanslack/Videomass#67]
due to changes mentioned previously for dependency versions not available in bionic:
https://github.com/jeanslack/Videomass/issues/18

```
[Python >= 3.7.0]
[wxPython-Phoenix >= 4.0.7]
[PyPubSub >= 4.0.3]
```

etc

**it may be prudent to stop updating the PPA for bionic version**

videomass v3.5.5 and v3.5.6 will fail dependencies

wxpython 4.0.7 cannot be installed
where the previous version can be
python3-wxgtk4.0_4.0.1+dfsg-2_amd64.deb
vs
python3-wxgtk4.0_4.0.7+dfsg-2build1_amd64.deb
https://packages.ubuntu.com/search?keywords=python3-wxgtk4

also because this is not avail to bionic
python3-pubsub_4.0.3-4_all.deb
this is a package from focal
https://packages.ubuntu.com/search?keywords=python3-pubsub

reverting to the version
python3-videomass_3.5.3-1_all.deb
with the patches NewRef https://github.com/jeanslack/Videomass/pull/52
everything works fine

**unless you intend to supply these backports to bionic on the PPA**
or inform the user that they will need to manually compile them or find backported sources elsewhere

note this doesnt effect the appimage released here
Videomass-3.5.6-x86_64.AppImage
this works fine in bionic.  and has nothing to do with the PPA versions

im making this issue here because you are the maintainer of the PPA
good luck!  thanks for support

**Comment by jeanslack** [comment]
I just deleted the Videomass v3.5.6 package for Ubuntu Bionic. Then I will no longer include PPA support for Bionic in future releases.
![Screenshot_20220228_222422](https://user-images.githubusercontent.com/8676484/156064297-f902ecfe-b362-480b-9b93-faa90e69bb42.png)

Thank you for reporting this issue.

**Comment by arrowgent** [comment]
probally a good choice overall,  if you were unable to re-upload a previous version

this prevents users from using the PPA and having a broken package because of dependencies (18.04)

thanks!
