### ISSUE TITLE
[feature] "open file" vs "drag and drop"

### ISSUE THREAD

**Issue by arrowgent** [jeanslack/Videomass#68]
im trying to understand if there is a way to `open a dialog for "open video file"` instead of dragging and dropping files on the window?

it seems unusual and very few software ive used _only allows_ for adding a file to the software by dragging it onto the window

**Comment by jeanslack** [comment]
Since the order in which the files are imported determines the final result for some functionality offered by the program, and since an import dialog would be less comfortable, I thought such an implementation was redundant. 
How did you have this need?

**Comment by arrowgent** [comment]
this really depends on usability and choice

given most of the time i have a file manager window open at fullscreen, i would have to shrink the size of the window to simultaneously click a file and drag it over to the other window
optionally make videomass "always on top" during this operation

where traditionally a `File` -> `Open` would be the first option someone would investigate
the dialog can have multiple files selected and properly selected in the order they were highlighted

"A" + "B" + "C" would go in the order
A
B
C
where clicking CTRL+ "C" "A" "B" would select and store the string of filenames as
C
A
B

other software has this capability, so this is why i was suggesting it here
no reason to require having a file manager open to use and interact with other software

this is partially already implemented of course when selecting ffmpeg, youtube-dl, download location and video location
a dialog box opens and prompts the location using the system file manager window

just my idea of course, i have no idea how well the UI capabilities of the software youre using our how you can figure that UI dialog option while maintaining the ordering string.

**Comment by jeanslack** [comment]
> "A" + "B" + "C" would go in the order
A
B
C
where clicking CTRL+ "C" "A" "B" would select and store the string of filenames as
C
A
B

Yes, but it appears to be currently only supported by wxGTK (ie only on Linux). This is a limitation that wx have.
Anyway I will add this option.
