### ISSUE TITLE
Feature request: NVENC presets

### ISSUE THREAD

**Issue by johannesdedoper** [jeanslack/Videomass#70]
Hello @jeanslack 

The main thing for users that can/will not use the FFmpeg code is to add presets voor NVENC.
If you need to have these tested I can help as I have a Nvidia GPU.
For me this is not a issue as I prefer to make my own presets but I can imagine the average user does want to use the build in presets.

Cheers,
J.

**Comment by jeanslack** [comment]
Hello @johannesdedoper 

If you want you can also write presets yourself. For changes, editing, new versions, sharing, etc, there is a dedicated repository, if you want to have a look it's here https://github.com/jeanslack/Videomass-presets
You can clone the entire repo locally and work on it.
Let me know...

**Comment by johannesdedoper** [comment]
Hello,
I forked the presets and uploaded 2 files (presets and readme). As I'm not sure what I'm doing here may be you can check?
Also have a look at the presets, these are my preferred presets and maybe not interesting for others?
cheers,
J.

**Comment by jeanslack** [comment]
Hello,
Thanks, this is Fantastic!
In my opinion your presets can be interesting for those who want to use a starting point with `NVidia accelerated video encoding`.
 
If you wish to integrate your presets into the official [Videomass Presets repo](https://github.com/jeanslack/Videomass-presets)  (upstream) and be able to download them using the Videomass version control system, you should read the guidelines below and then create a [Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

GUIDELINES:
You should create a folder with a descriptive name, e.g. `NVidia-accelerated-video-encoding`, in which you will put  `NVENC_h265_presets.prst` file and the `README presets.txt` file. Furthermore, it is required to create a folder called "version" in which you will have to create the text file `version.txt` which reports the version of your presets.
Help yourself by looking at the data already present on the other presets folders.

If you can't do all of this, let me know and I'll do it myself. 

Have a Good Day!

**Comment by johannesdedoper** [comment]
Hello,
Thanks, but I have no idea how to do this, maybe you can do this? Would be great.
I'm not familiar with this and it will probably take a lot of time for me. 
cheers, 
J.

**Comment by jeanslack** [comment]
OK, now your presets are included in the v0.6 release.
Thank you for your contribution.

**Comment by johannesdedoper** [comment]
Nice, your welcome!
