### ISSUE TITLE
Install instructions wrong for linux

### ISSUE THREAD

**Issue by PinkPlasticBeach** [jeanslack/Videomass#83]
Hey there,
On this Page:
https://jeanslack.github.io/Videomass/Pages/Packages/Linux.html
Install instructions for the repository say 

$ sudo ADD-APT-repository ppa:jeanslack/videomass 

It should be 
$ sudo apt-add-repository ppa:jeanslack/videomass 

I think. It gives me an error in ubuntu 20.04
Just a typo I guess. No problem for people who know apt but for copy-paste-terminaleros :)
Kind regards

**Comment by jeanslack** [comment]
Hello @PinkPlasticBeach,

Thought the instructions on how to add the [PPA](https://launchpad.net/+help-soyuz/ppa-sources-list.html), read on the https://launchpad.net/~jeanslack/+archive/ubuntu/videomass web page, were correct as they are official. 
Anyway thanks for reporting this error, I will correct it immediately.
Greetings
