### ISSUE TITLE
Bug appearance?

### ISSUE THREAD

**Issue by johannesdedoper** [jeanslack/Videomass#88]
Hello @jeanslack,

tried to change to darkmode, tried both breeze and videomass dark.
Both change but not to some sort of darkmode (see picture)
I'm using the appimage 3.5.7. on PopOS 21.10.

Cheers,
J.
![app](https://user-images.githubusercontent.com/100475891/158834599-32250818-b275-46bc-a198-2864b5725153.png)

**Comment by jeanslack** [comment]
Hello @johannesdedoper,

That's not a bug. Changing the icon theme on Videomass preferences only the icons and some text field backgrounds/foregrounds change. If you want to completely change the theme you should do it system-wide with your theme manager. Next you will set the Videomass icons theme according to dark/light theme used.
