### ISSUE TITLE
Question: speed

### ISSUE THREAD

**Issue by johannesdedoper** [jeanslack/Videomass#92]
Hello @jeanslack,

Please delete this issue, found an possible answer.

**Comment by jeanslack** [comment]
Hello @johannesdedoper,

OK, anyway if you don't solve it try posting the log here and let's take a look at it.

**Comment by johannesdedoper** [comment]
Hello @jeanslack ,

the thing is that Handbrake can do an HEVC NVenc encoding with a vbr of 2600k medium preset with 270fps and Videomass  with same settings comes to 170 fps. With the fast preset Videomass will do 270fps+ (between 300 even 600fps!!). Handbrake will stay with the fast en faster preset at 270fps however. Strange? Seems that the combination of bitrate encoding and presets are not doing anything within Handbrake. 
Also Handbrake takes up much more CPU power (40% +) compared to Videomass (6 - 10%).

Just wondering why the different behaviour? Eg. Cinecoder shows the same behaviour as Videomass. Xvid4PSP seems to be using the fast preset as standard as it encodes the files with 300-600 fps and almost no CPU usage.

It's not really important as the fast preset gives nearly the same quality and filesize as the medium preset (within 3% - 6%).
But I'm just curious.

Cheers,
J.

**Comment by jeanslack** [comment]
I would be curious too, but not having now the ability to use hardware acceleration...
Check out this thread if it helps https://superuser.com/questions/1296374/best-settings-for-ffmpeg-with-nvenc

Cheers
